version: "2"

run:
  timeout: 5m
  issues-exit-code: 42

output:
  formats:
    text:
      path: stdout
      color: true

linters:
  disable-all: true
  settings:
    depguard:
      rules:
        no-direct-zerolog-log:
          list-mode: lax
          files:
            - "!**/internal/log/**"
          deny:
            - pkg: "github.com/rs/zerolog/log"
              desc: "use go.zpotify.ru/zpotify/internal/log instead"
    govet:
      enable:
        - shadow
    varnamelen:
      max-distance: 25
      min-name-length: 2
      ignore-type-assert-ok: true
      check-type-param: true
      ignore-chan-recv-ok: true
  enable:
    - varnamelen
    - govet

    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl

issues:
  exclude-dirs:
    - configs
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA9003:"
    - linters:
        - lll
      source: "^//go:generate "
