-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS users
(
    id          INT2 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tg_id       INT8 NOT NULL UNIQUE,
    tg_username TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS locales
(
    id TEXT PRIMARY KEY
);

INSERT INTO locales (id)
VALUES ('en'),
       ('ru')
ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS user_settings
(
    user_id INT2 REFERENCES users (id) UNIQUE,
    locale  TEXT REFERENCES locales (id) NOT NULL DEFAULT 'en'
);

CREATE TABLE IF NOT EXISTS user_permissions
(
    user_id             INT2 REFERENCES users (id),
    can_upload          BOOL    DEFAULT false NOT NULL,
    early_access        BOOL    DEFAULT false NOT NULL,
    can_create_playlist BOOLEAN DEFAULT false NOT NULL
);

CREATE TABLE IF NOT EXISTS files_meta
(
    id           INT4 NOT NULL PRIMARY KEY GENERATED ALWAYS AS identity,
    file_path    TEXT NOT NULL,
    duration_sec INT4 NOT NULL,
    added_by_id  INT2 NOT NULL REFERENCES users (id),
    size_bytes   INT4
);

CREATE TABLE IF NOT EXISTS user_sessions
(
    user_id           INT2 REFERENCES users (id),

    access_token      TEXT PRIMARY KEY,
    refresh_token     TEXT UNIQUE,
    access_expire_at  TIMESTAMP,
    refresh_expire_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS artists
(
    uuid UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS songs
(
    id         INT4 PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    file_id    INT4 REFERENCES files_meta (id),
    title      TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE IF NOT EXISTS songs_artists
(
    song_id     INT4 REFERENCES songs (id)     NOT NULL,
    artist_uuid UUID REFERENCES artists (uuid) NOT NULL,
    order_id    INT2                           NOT NULL,
    UNIQUE (song_id, order_id),
    UNIQUE (song_id, artist_uuid)
);


-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

-- +goose StatementEnd
