// Code generated by RedSock CLI.
// DO EDIT, DON'T DELETE THIS FILE.

package app

import (
	"context"
	"time"

	"github.com/Red-Sock/go_tg"
	"github.com/rs/zerolog/log"
	"go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc"
	"go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"
	"go.redsock.ru/rerrors"
	"golang.org/x/sync/errgroup"
	"google.golang.org/grpc"

	"go.zpotify.ru/zpotify/internal/api/server/zpotify_api"
	"go.zpotify.ru/zpotify/internal/async"
	ap_handler "go.zpotify.ru/zpotify/internal/async/handlers/audio_parser"
	gc_handler "go.zpotify.ru/zpotify/internal/async/handlers/garbage_collector"
	"go.zpotify.ru/zpotify/internal/async/provider/pgqueue"
	"go.zpotify.ru/zpotify/internal/background"
	"go.zpotify.ru/zpotify/internal/background/sessions_gc"
	"go.zpotify.ru/zpotify/internal/middleware"
	"go.zpotify.ru/zpotify/internal/service"
	"go.zpotify.ru/zpotify/internal/storage"
	"go.zpotify.ru/zpotify/internal/storage/file_storage_providers"
	"go.zpotify.ru/zpotify/internal/storage/files_cache"
	"go.zpotify.ru/zpotify/internal/storage/pg"
	"go.zpotify.ru/zpotify/internal/transport"
	"go.zpotify.ru/zpotify/internal/transport/artists_api_impl"
	"go.zpotify.ru/zpotify/internal/transport/auth_api_impl"
	"go.zpotify.ru/zpotify/internal/transport/file_api_impl"
	"go.zpotify.ru/zpotify/internal/transport/playlist_api_impl"
	"go.zpotify.ru/zpotify/internal/transport/song_api_impl"
	telegramtransport "go.zpotify.ru/zpotify/internal/transport/telegram"
	"go.zpotify.ru/zpotify/internal/transport/ui"
	"go.zpotify.ru/zpotify/internal/transport/user_api_impl"
	"go.zpotify.ru/zpotify/internal/transport/wapi"
	"go.zpotify.ru/zpotify/pkg/docs"
)

type Custom struct {
	dataStorage   storage.Storage
	binaryStorage storage.BinaryFileStorage
	tgConn        go_tg.TgApi

	Service service.Service

	BackgroundWorker *background.Worker
	AsyncPool        *async.Pool

	ArtistsApiImpl  *artists_api_impl.Impl
	AuthApiImpl     *auth_api_impl.Impl
	FileApiImpl     *file_api_impl.Impl
	UserApiImpl     *user_api_impl.Impl
	PlaylistApiImpl *playlist_api_impl.Impl
	SongApiImpl     *song_api_impl.Impl

	ServerManager  *transport.ServersManager
	telegramServer *telegramtransport.Server
}

func (c *Custom) Init(a *App) (err error) {
	rerrors.SetSeparator(':')

	err = a.initOTel()
	if err != nil {
		return rerrors.Wrap(err, "init otel")
	}
	if a.Cfg.Environment.OtelEndpoint != "" {
		hook := middleware.NewOtelLogHook("zpotify")
		log.Logger = log.Logger.Hook(hook)
	}

	c.dataStorage = pg.NewStorage(a.Postgres)
	c.binaryStorage, err = file_storage_providers.NewLocalStorageProvider(a.Cfg.Environment.LocalStoragePath)
	if err != nil {
		return rerrors.Wrap(err, "error creating local file storage provider")
	}
	c.tgConn, err = go_tg.NewBot("",
		go_tg.WithProxy(""))
	if err != nil {
		return rerrors.Wrap(err, "")
	}

	fc, err := files_cache.New()
	if err != nil {
		return rerrors.Wrap(err, "error creating files cache")
	}

	c.Service, err = service.New(c.dataStorage, fc, c.binaryStorage)
	if err != nil {
		return rerrors.Wrap(err, "error creating service")
	}

	c.BackgroundWorker = background.New(
		sessions_gc.New(c.dataStorage),
	)

	gcHandler := gc_handler.New(c.binaryStorage)
	gcProvider := pgqueue.New[storage.GarbageFilePayload](
		a.Cfg.DataSources.Postgres.ConnectionString(),
		c.dataStorage.Jobs(),
		storage.QueueNameGarbageCollector,
		gcHandler.Handle,
		60*time.Second,
	)

	apHandler := ap_handler.New(c.dataStorage.FileMeta(), c.binaryStorage)
	apProvider := pgqueue.New[storage.AudioParsePayload](
		a.Cfg.DataSources.Postgres.ConnectionString(),
		c.dataStorage.Jobs(),
		storage.QueueNameAudioParser,
		apHandler.Handle,
		60*time.Second,
	)

	c.AsyncPool = async.New(gcProvider, apProvider)

	c.ArtistsApiImpl = artists_api_impl.New(c.Service)
	c.AuthApiImpl = auth_api_impl.New(c.Service, a.Cfg.Environment.TelegramClientID)
	c.FileApiImpl = file_api_impl.New(c.Service)
	c.UserApiImpl = user_api_impl.New(c.Service)
	c.PlaylistApiImpl = playlist_api_impl.New(c.Service)
	c.SongApiImpl = song_api_impl.New(c.Service)

	c.ServerManager, err = transport.NewServerManager(a.Ctx, a.MASTER)
	if err != nil {
		return rerrors.Wrap(err, "error creating server manager")
	}

	otelServerHandler := otelgrpc.NewServerHandler()
	c.ServerManager.AddServerOption(
		middleware.PanicInterceptor(),
		middleware.TraceInterceptor(),
		middleware.LogInterceptor(),
		grpc.StatsHandler(otelServerHandler),
		middleware.GrpcAuthInterceptor(
			c.Service,
			middleware.WithIgnoredPathAuthOption(
				zpotify_api.AuthAPI_Auth_FullMethodName,
				zpotify_api.AuthAPI_RefreshToken_FullMethodName,
				zpotify_api.AuthAPI_AuthAsync_FullMethodName,
				zpotify_api.AuthAPI_GetAuthMethods_FullMethodName,
			),
			middleware.WithDebug(a.Cfg.Environment.DebugAuth),
		),
	)

	c.ServerManager.AddImplementation(
		c.ArtistsApiImpl,
		c.AuthApiImpl,
		c.FileApiImpl,
		c.UserApiImpl,
		c.SongApiImpl,
		c.PlaylistApiImpl,
	)

	c.ServerManager.AddHttpHandler(docs.Swagger())

	audioService := c.Service.AudioService()
	fileService := c.Service.FileService()

	wapiHandler := wapi.New(audioService, fileService)
	wapiHandler = middleware.HttpAuthMiddleware(
		c.Service,
		middleware.WithDebug(a.Cfg.Environment.DebugAuth),
	)(wapiHandler)
	wapiHandler = middleware.CorsMiddleware(a.Cfg.Environment.CorsAllowedOrigins)(wapiHandler)
	wapiHandler = middleware.LogWebMiddleware(wapiHandler)

	wapiHandler = otelhttp.NewHandler(wapiHandler, "/wapi")
	c.ServerManager.AddHttpHandler("/wapi/", wapiHandler)
	c.ServerManager.AddHttpHandler("/", ui.NewHandler())

	return nil
}

// Start - launch custom handlers
// Even if you won't use it keep it for proper work
func (c *Custom) Start(ctx context.Context) error {
	eg, ctx := errgroup.WithContext(ctx)

	eg.Go(c.BackgroundWorker.Start)
	eg.Go(c.AsyncPool.Start)

	eg.Go(c.ServerManager.Start)

	err := eg.Wait()
	if err != nil {
		return rerrors.Wrap(err)
	}

	return nil
}

// Stop - gracefully stop custom handlers
// Even if you won't use it keep it for proper work
func (c *Custom) Stop() error {
	eg := errgroup.Group{}

	eg.Go(func() error {
		return c.BackgroundWorker.Stop()
	})
	eg.Go(func() error {
		return c.AsyncPool.Stop()
	})
	eg.Go(c.ServerManager.Stop)

	err := eg.Wait()
	if err != nil {
		return rerrors.Wrap(err)
	}
	return nil
}
