// Code generated by RedSock CLI.
// DO EDIT, DON'T DELETE THIS FILE.

package app

import (
	"context"
	"time"

	"github.com/Red-Sock/go_tg"
	"github.com/Red-Sock/go_tg/model/response"
	"github.com/anacrolix/torrent"
	"github.com/rs/zerolog/log"
	"go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc"
	"go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"
	"go.redsock.ru/rerrors"
	"golang.org/x/sync/errgroup"
	"google.golang.org/grpc"

	"go.zpotify.ru/zpotify/internal/api/server/zpotify_api"
	"go.zpotify.ru/zpotify/internal/async"
	ap_handler "go.zpotify.ru/zpotify/internal/async/handlers/audio_parser"
	gc_handler "go.zpotify.ru/zpotify/internal/async/handlers/garbage_collector"
	"go.zpotify.ru/zpotify/internal/async/provider/pgqueue"
	"go.zpotify.ru/zpotify/internal/background"
	"go.zpotify.ru/zpotify/internal/background/sessions_gc"
	"go.zpotify.ru/zpotify/internal/background/torrent_sync"
	tgclient "go.zpotify.ru/zpotify/internal/clients/telegram"
	"go.zpotify.ru/zpotify/internal/middleware"
	"go.zpotify.ru/zpotify/internal/service"
	v1 "go.zpotify.ru/zpotify/internal/service/v1"
	"go.zpotify.ru/zpotify/internal/storage"
	"go.zpotify.ru/zpotify/internal/storage/file_storage_providers"
	"go.zpotify.ru/zpotify/internal/storage/files_cache"
	"go.zpotify.ru/zpotify/internal/storage/pg"
	"go.zpotify.ru/zpotify/internal/transport"
	"go.zpotify.ru/zpotify/internal/transport/artists_api_impl"
	"go.zpotify.ru/zpotify/internal/transport/auth_api_impl"
	"go.zpotify.ru/zpotify/internal/transport/feature_flags_api_impl"
	"go.zpotify.ru/zpotify/internal/transport/file_api_impl"
	"go.zpotify.ru/zpotify/internal/transport/home_api_impl"
	"go.zpotify.ru/zpotify/internal/transport/notification_api_impl"
	"go.zpotify.ru/zpotify/internal/transport/playlist_api_impl"
	"go.zpotify.ru/zpotify/internal/transport/search_api_impl"
	"go.zpotify.ru/zpotify/internal/transport/song_api_impl"
	"go.zpotify.ru/zpotify/internal/transport/telegram/grant_access"
	"go.zpotify.ru/zpotify/internal/transport/telegram/grant_creator_access"
	"go.zpotify.ru/zpotify/internal/transport/telegram/notify"
	"go.zpotify.ru/zpotify/internal/transport/torrent_api_impl"
	"go.zpotify.ru/zpotify/internal/transport/ui"
	"go.zpotify.ru/zpotify/internal/transport/user_api_impl"
	"go.zpotify.ru/zpotify/internal/transport/wapi"
	"go.zpotify.ru/zpotify/pkg/docs"
)

type Custom struct {
	dataStorage   storage.Storage
	binaryStorage storage.BinaryFileStorage
	tgConn        go_tg.TgApi
	torrentClient *torrent.Client

	Service service.Service

	BackgroundWorker *background.Worker
	AsyncPool        *async.Pool

	ArtistsApiImpl   *artists_api_impl.Impl
	AuthApiImpl      *auth_api_impl.Impl
	FeatureFlagsImpl *feature_flags_api_impl.Impl
	FileApiImpl      *file_api_impl.Impl
	UserApiImpl      *user_api_impl.Impl
	PlaylistApiImpl  *playlist_api_impl.Impl
	SongApiImpl      *song_api_impl.Impl
	HomeApiImpl      *home_api_impl.Impl
	NotificationImpl *notification_api_impl.Impl
	SearchApiImpl    *search_api_impl.Impl
	TorrentApiImpl   *torrent_api_impl.Impl

	ServerManager *transport.ServersManager
}

func (c *Custom) Init(app *App) (err error) {
	rerrors.SetSeparator(':')

	err = app.initOTel()
	if err != nil {
		return rerrors.Wrap(err, "init otel")
	}
	if app.Cfg.Environment.OtelEndpoint != "" {
		hook := middleware.NewOtelLogHook("zpotify")
		log.Logger = log.Logger.Hook(hook)
	}

	c.dataStorage = pg.NewStorage(app.Postgres)
	c.binaryStorage, err = file_storage_providers.NewLocalStorageProvider(app.Cfg.Environment.LocalStoragePath)
	if err != nil {
		return rerrors.Wrap(err, "error creating local file storage provider")
	}

	torrentClientCfg := v1.TorrentClientConfig{
		DownloadDir: app.Cfg.Environment.TorrentDownloadDir,
		ListenPort:  app.Cfg.Environment.TorrentListenPort,
		Seed:        app.Cfg.Environment.TorrentSeedAfterComplete,
	}

	c.torrentClient, err = v1.NewTorrentClient(torrentClientCfg)
	if err != nil {
		return rerrors.Wrap(err, "error creating torrent client")
	}

	if app.Cfg.Environment.TelegramProxyURL != "" {
		c.tgConn, err = go_tg.NewBot(app.Cfg.Environment.TelegramToken,
			go_tg.WithProxy(app.Cfg.Environment.TelegramProxyURL))
	} else {
		c.tgConn, err = go_tg.NewBot(app.Cfg.Environment.TelegramToken)
	}
	if err != nil {
		return rerrors.Wrap(err, "")
	}

	adminNotifier := tgclient.NewAdminNotifier(c.tgConn, int64(app.Cfg.Environment.TelegramNotificationsChatID))
	trackSender := tgclient.NewTrackSender(c.tgConn)

	fc, err := files_cache.New()
	if err != nil {
		return rerrors.Wrap(err, "error creating files cache")
	}

	torrentServiceCfg := v1.TorrentServiceConfig{
		DownloadDir:            app.Cfg.Environment.TorrentDownloadDir,
		MaxConcurrentDownloads: app.Cfg.Environment.TorrentMaxConcurrentDownloads,
		SeedAfterComplete:      app.Cfg.Environment.TorrentSeedAfterComplete,
		SeedTimeLimitMinutes:   app.Cfg.Environment.TorrentSeedTimeLimitMinutes,
	}

	torrentService := v1.NewTorrentService(c.dataStorage, c.binaryStorage, c.torrentClient, torrentServiceCfg)

	c.Service, err = service.New(c.dataStorage, fc, c.binaryStorage, adminNotifier, trackSender, torrentService, app.Cfg)
	if err != nil {
		return rerrors.Wrap(err, "error creating service")
	}

	c.tgConn.MustAddCommandHandler(grant_access.New(c.Service.UserService(), int64(app.Cfg.Environment.TelegramNotificationsChatID)))
	c.tgConn.MustAddCommandHandler(grant_creator_access.New(c.Service.UserService(), int64(app.Cfg.Environment.TelegramNotificationsChatID)))
	c.tgConn.MustAddCommandHandler(notify.New(c.Service.NotificationService(), int64(app.Cfg.Environment.TelegramNotificationsChatID)))
	c.tgConn.MustAddCommandHandler(notify.NewConsent(c.Service.NotificationService(), int64(app.Cfg.Environment.TelegramNotificationsChatID)))

	torrentLookup := torrent_sync.NewClientLookup(c.torrentClient)
	torrentSyncPeriod := time.Duration(app.Cfg.Environment.TorrentSyncPeriodSeconds) * time.Second

	c.BackgroundWorker = background.New(
		sessions_gc.New(c.dataStorage),
		torrent_sync.New(c.dataStorage, torrentLookup, torrentService, torrentSyncPeriod),
	)

	gcHandler := gc_handler.New(c.binaryStorage)
	gcProvider := pgqueue.New[storage.GarbageFilePayload](
		app.Cfg.DataSources.Postgres.ConnectionString(),
		c.dataStorage.Jobs(),
		storage.QueueNameGarbageCollector,
		gcHandler.Handle,
		60*time.Second,
	)

	apHandler := ap_handler.New(c.dataStorage.FileMeta(), c.binaryStorage)
	apProvider := pgqueue.New[storage.AudioParsePayload](
		app.Cfg.DataSources.Postgres.ConnectionString(),
		c.dataStorage.Jobs(),
		storage.QueueNameAudioParser,
		apHandler.Handle,
		60*time.Second,
	)

	c.AsyncPool = async.New(gcProvider, apProvider)

	c.ArtistsApiImpl = artists_api_impl.New(c.Service)
	c.AuthApiImpl = auth_api_impl.New(c.Service, app.Cfg.Environment.TelegramClientID)
	c.FeatureFlagsImpl = feature_flags_api_impl.New(c.Service)
	c.FileApiImpl = file_api_impl.New(c.Service)
	c.UserApiImpl = user_api_impl.New(c.Service)
	c.PlaylistApiImpl = playlist_api_impl.New(c.Service)
	c.SongApiImpl = song_api_impl.New(c.Service)
	c.HomeApiImpl = home_api_impl.New(c.Service)
	c.NotificationImpl = notification_api_impl.New(c.Service)
	c.SearchApiImpl = search_api_impl.New(c.Service)
	c.TorrentApiImpl = torrent_api_impl.New(c.Service)

	c.ServerManager, err = transport.NewServerManager(app.Ctx, app.MASTER)
	if err != nil {
		return rerrors.Wrap(err, "error creating server manager")
	}

	otelServerHandler := otelgrpc.NewServerHandler()
	c.ServerManager.AddServerOption(
		middleware.PanicInterceptor(),
		middleware.TraceInterceptor(),
		middleware.LogInterceptor(),
		grpc.StatsHandler(otelServerHandler),
		middleware.GrpcAuthInterceptor(
			c.Service,
			middleware.WithIgnoredPathAuthOption(
				zpotify_api.AuthAPI_Auth_FullMethodName,
				zpotify_api.AuthAPI_RefreshToken_FullMethodName,
				zpotify_api.AuthAPI_AuthAsync_FullMethodName,
				zpotify_api.AuthAPI_GetAuthMethods_FullMethodName,
				zpotify_api.FeatureFlagsAPI_GetFeatureFlags_FullMethodName,
			),
			middleware.WithDebug(app.Cfg.Environment.DebugAuth),
		),
	)

	c.ServerManager.AddImplementation(
		c.ArtistsApiImpl,
		c.AuthApiImpl,
		c.FeatureFlagsImpl,
		c.FileApiImpl,
		c.UserApiImpl,
		c.SongApiImpl,
		c.PlaylistApiImpl,
		c.HomeApiImpl,
		c.NotificationImpl,
		c.SearchApiImpl,
		c.TorrentApiImpl,
	)

	c.ServerManager.AddHttpHandler(docs.Swagger())

	audioService := c.Service.AudioService()
	fileService := c.Service.FileService()

	wapiHandler := wapi.New(audioService, fileService, torrentService)
	wapiHandler = middleware.HttpAuthMiddleware(
		c.Service,
		middleware.WithDebug(app.Cfg.Environment.DebugAuth),
	)(wapiHandler)
	wapiHandler = middleware.CorsMiddleware(app.Cfg.Environment.CorsAllowedOrigins)(wapiHandler)
	wapiHandler = middleware.LogWebMiddleware(wapiHandler)

	wapiHandler = otelhttp.NewHandler(wapiHandler, "/wapi")
	c.ServerManager.AddHttpHandler("/wapi/", wapiHandler)
	c.ServerManager.AddHttpHandler("/", ui.NewHandler())

	if app.Cfg.Environment.TelegramNotificationsChatID != 0 {
		startMessage := &response.MessageOut{
			ChatId: int64(app.Cfg.Environment.TelegramNotificationsChatID),
			Text:   "Application started",
		}

		err = c.tgConn.Send(startMessage)
		if err != nil {
			log.Err(err).Msg("error sending start pod message")
		}
	}

	return nil
}

// Start - launch custom handlers
// Even if you won't use it keep it for proper work.
func (c *Custom) Start(ctx context.Context) error {
	eg, _ := errgroup.WithContext(ctx)

	eg.Go(c.BackgroundWorker.Start)
	eg.Go(c.AsyncPool.Start)

	eg.Go(c.ServerManager.Start)

	eg.Go(func() error {
		startErr := c.tgConn.Start()
		if startErr != nil {
			return rerrors.Wrap(startErr, "error starting telegram bot")
		}
		return nil
	})

	err := eg.Wait()
	if err != nil {
		return rerrors.Wrap(err)
	}

	return nil
}

// Stop - gracefully stop custom handlers
// Even if you won't use it keep it for proper work.
func (c *Custom) Stop() error {
	eg := errgroup.Group{}

	eg.Go(func() error {
		return c.BackgroundWorker.Stop()
	})
	eg.Go(func() error {
		return c.AsyncPool.Stop()
	})
	eg.Go(c.ServerManager.Stop)
	eg.Go(func() error {
		c.tgConn.Stop()
		return nil
	})
	eg.Go(func() error {
		if c.torrentClient == nil {
			return nil
		}

		closeErrs := c.torrentClient.Close()
		for _, closeErr := range closeErrs {
			log.Err(closeErr).Msg("error closing torrent client")
		}

		return nil
	})

	err := eg.Wait()
	if err != nil {
		return rerrors.Wrap(err)
	}
	return nil
}
