// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: zpotify_service_song.proto

package zpotify_api

import (
	_ "go.redsock.ru/protoc-gen-npm/npmplugin"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSong) Reset() {
	*x = CreateSong{}
	mi := &file_zpotify_service_song_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSong) ProtoMessage() {}

func (x *CreateSong) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_song_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSong.ProtoReflect.Descriptor instead.
func (*CreateSong) Descriptor() ([]byte, []int) {
	return file_zpotify_service_song_proto_rawDescGZIP(), []int{0}
}

type BatchCreateSong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateSong) Reset() {
	*x = BatchCreateSong{}
	mi := &file_zpotify_service_song_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateSong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateSong) ProtoMessage() {}

func (x *BatchCreateSong) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_song_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateSong.ProtoReflect.Descriptor instead.
func (*BatchCreateSong) Descriptor() ([]byte, []int) {
	return file_zpotify_service_song_proto_rawDescGZIP(), []int{1}
}

type UpdateSong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSong) Reset() {
	*x = UpdateSong{}
	mi := &file_zpotify_service_song_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSong) ProtoMessage() {}

func (x *UpdateSong) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_song_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSong.ProtoReflect.Descriptor instead.
func (*UpdateSong) Descriptor() ([]byte, []int) {
	return file_zpotify_service_song_proto_rawDescGZIP(), []int{2}
}

type GetSong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSong) Reset() {
	*x = GetSong{}
	mi := &file_zpotify_service_song_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSong) ProtoMessage() {}

func (x *GetSong) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_song_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSong.ProtoReflect.Descriptor instead.
func (*GetSong) Descriptor() ([]byte, []int) {
	return file_zpotify_service_song_proto_rawDescGZIP(), []int{3}
}

type SearchSongs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSongs) Reset() {
	*x = SearchSongs{}
	mi := &file_zpotify_service_song_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSongs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSongs) ProtoMessage() {}

func (x *SearchSongs) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_song_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSongs.ProtoReflect.Descriptor instead.
func (*SearchSongs) Descriptor() ([]byte, []int) {
	return file_zpotify_service_song_proto_rawDescGZIP(), []int{4}
}

type CreateSong_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	ArtistUuids   []string               `protobuf:"bytes,2,rep,name=artist_uuids,json=artistUuids,proto3" json:"artist_uuids,omitempty"`
	FileId        int64                  `protobuf:"varint,3,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSong_Request) Reset() {
	*x = CreateSong_Request{}
	mi := &file_zpotify_service_song_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSong_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSong_Request) ProtoMessage() {}

func (x *CreateSong_Request) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_song_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSong_Request.ProtoReflect.Descriptor instead.
func (*CreateSong_Request) Descriptor() ([]byte, []int) {
	return file_zpotify_service_song_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CreateSong_Request) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateSong_Request) GetArtistUuids() []string {
	if x != nil {
		return x.ArtistUuids
	}
	return nil
}

func (x *CreateSong_Request) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

type CreateSong_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSong_Response) Reset() {
	*x = CreateSong_Response{}
	mi := &file_zpotify_service_song_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSong_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSong_Response) ProtoMessage() {}

func (x *CreateSong_Response) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_song_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSong_Response.ProtoReflect.Descriptor instead.
func (*CreateSong_Response) Descriptor() ([]byte, []int) {
	return file_zpotify_service_song_proto_rawDescGZIP(), []int{0, 1}
}

func (x *CreateSong_Response) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BatchCreateSong_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Songs         []*CreateSong_Request  `protobuf:"bytes,1,rep,name=songs,proto3" json:"songs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateSong_Request) Reset() {
	*x = BatchCreateSong_Request{}
	mi := &file_zpotify_service_song_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateSong_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateSong_Request) ProtoMessage() {}

func (x *BatchCreateSong_Request) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_song_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateSong_Request.ProtoReflect.Descriptor instead.
func (*BatchCreateSong_Request) Descriptor() ([]byte, []int) {
	return file_zpotify_service_song_proto_rawDescGZIP(), []int{1, 0}
}

func (x *BatchCreateSong_Request) GetSongs() []*CreateSong_Request {
	if x != nil {
		return x.Songs
	}
	return nil
}

type BatchCreateSong_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateSong_Response) Reset() {
	*x = BatchCreateSong_Response{}
	mi := &file_zpotify_service_song_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateSong_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateSong_Response) ProtoMessage() {}

func (x *BatchCreateSong_Response) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_song_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateSong_Response.ProtoReflect.Descriptor instead.
func (*BatchCreateSong_Response) Descriptor() ([]byte, []int) {
	return file_zpotify_service_song_proto_rawDescGZIP(), []int{1, 1}
}

func (x *BatchCreateSong_Response) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type UpdateSong_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ArtistUuids   []string               `protobuf:"bytes,3,rep,name=artist_uuids,json=artistUuids,proto3" json:"artist_uuids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSong_Request) Reset() {
	*x = UpdateSong_Request{}
	mi := &file_zpotify_service_song_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSong_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSong_Request) ProtoMessage() {}

func (x *UpdateSong_Request) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_song_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSong_Request.ProtoReflect.Descriptor instead.
func (*UpdateSong_Request) Descriptor() ([]byte, []int) {
	return file_zpotify_service_song_proto_rawDescGZIP(), []int{2, 0}
}

func (x *UpdateSong_Request) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateSong_Request) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateSong_Request) GetArtistUuids() []string {
	if x != nil {
		return x.ArtistUuids
	}
	return nil
}

type UpdateSong_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSong_Response) Reset() {
	*x = UpdateSong_Response{}
	mi := &file_zpotify_service_song_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSong_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSong_Response) ProtoMessage() {}

func (x *UpdateSong_Response) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_song_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSong_Response.ProtoReflect.Descriptor instead.
func (*UpdateSong_Response) Descriptor() ([]byte, []int) {
	return file_zpotify_service_song_proto_rawDescGZIP(), []int{2, 1}
}

type GetSong_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSong_Request) Reset() {
	*x = GetSong_Request{}
	mi := &file_zpotify_service_song_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSong_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSong_Request) ProtoMessage() {}

func (x *GetSong_Request) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_song_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSong_Request.ProtoReflect.Descriptor instead.
func (*GetSong_Request) Descriptor() ([]byte, []int) {
	return file_zpotify_service_song_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetSong_Request) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetSong_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Song          *SongBase              `protobuf:"bytes,1,opt,name=song,proto3" json:"song,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSong_Response) Reset() {
	*x = GetSong_Response{}
	mi := &file_zpotify_service_song_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSong_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSong_Response) ProtoMessage() {}

func (x *GetSong_Response) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_song_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSong_Response.ProtoReflect.Descriptor instead.
func (*GetSong_Response) Descriptor() ([]byte, []int) {
	return file_zpotify_service_song_proto_rawDescGZIP(), []int{3, 1}
}

func (x *GetSong_Response) GetSong() *SongBase {
	if x != nil {
		return x.Song
	}
	return nil
}

type SearchSongs_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Paging        *Paging                `protobuf:"bytes,2,opt,name=paging,proto3" json:"paging,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSongs_Request) Reset() {
	*x = SearchSongs_Request{}
	mi := &file_zpotify_service_song_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSongs_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSongs_Request) ProtoMessage() {}

func (x *SearchSongs_Request) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_song_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSongs_Request.ProtoReflect.Descriptor instead.
func (*SearchSongs_Request) Descriptor() ([]byte, []int) {
	return file_zpotify_service_song_proto_rawDescGZIP(), []int{4, 0}
}

func (x *SearchSongs_Request) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchSongs_Request) GetPaging() *Paging {
	if x != nil {
		return x.Paging
	}
	return nil
}

type SearchSongs_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Songs         []*SongBase            `protobuf:"bytes,1,rep,name=songs,proto3" json:"songs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSongs_Response) Reset() {
	*x = SearchSongs_Response{}
	mi := &file_zpotify_service_song_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSongs_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSongs_Response) ProtoMessage() {}

func (x *SearchSongs_Response) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_song_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSongs_Response.ProtoReflect.Descriptor instead.
func (*SearchSongs_Response) Descriptor() ([]byte, []int) {
	return file_zpotify_service_song_proto_rawDescGZIP(), []int{4, 1}
}

func (x *SearchSongs_Response) GetSongs() []*SongBase {
	if x != nil {
		return x.Songs
	}
	return nil
}

var File_zpotify_service_song_proto protoreflect.FileDescriptor

const file_zpotify_service_song_proto_rawDesc = "" +
	"\n" +
	"\x1azpotify_service_song.proto\x12\vzpotify_api\x1a\x1cgoogle/api/annotations.proto\x1a\tnpm.proto\x1a\x14zpotify_common.proto\"\x85\x01\n" +
	"\n" +
	"CreateSong\x1a[\n" +
	"\aRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12!\n" +
	"\fartist_uuids\x18\x02 \x03(\tR\vartistUuids\x12\x17\n" +
	"\afile_id\x18\x03 \x01(\x03R\x06fileId\x1a\x1a\n" +
	"\bResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"q\n" +
	"\x0fBatchCreateSong\x1a@\n" +
	"\aRequest\x125\n" +
	"\x05songs\x18\x01 \x03(\v2\x1f.zpotify_api.CreateSong.RequestR\x05songs\x1a\x1c\n" +
	"\bResponse\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"l\n" +
	"\n" +
	"UpdateSong\x1aR\n" +
	"\aRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12!\n" +
	"\fartist_uuids\x18\x03 \x03(\tR\vartistUuids\x1a\n" +
	"\n" +
	"\bResponse\"[\n" +
	"\aGetSong\x1a\x19\n" +
	"\aRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x1a5\n" +
	"\bResponse\x12)\n" +
	"\x04song\x18\x01 \x01(\v2\x15.zpotify_api.SongBaseR\x04song\"\x94\x01\n" +
	"\vSearchSongs\x1aL\n" +
	"\aRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12+\n" +
	"\x06paging\x18\x02 \x01(\v2\x13.zpotify_api.PagingR\x06paging\x1a7\n" +
	"\bResponse\x12+\n" +
	"\x05songs\x18\x01 \x03(\v2\x15.zpotify_api.SongBaseR\x05songs2\xba\x04\n" +
	"\aSongAPI\x12l\n" +
	"\n" +
	"CreateSong\x12\x1f.zpotify_api.CreateSong.Request\x1a .zpotify_api.CreateSong.Response\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/song/create\x12\x81\x01\n" +
	"\x0fBatchCreateSong\x12$.zpotify_api.BatchCreateSong.Request\x1a%.zpotify_api.BatchCreateSong.Response\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/song/batch_create\x12l\n" +
	"\n" +
	"UpdateSong\x12\x1f.zpotify_api.UpdateSong.Request\x1a .zpotify_api.UpdateSong.Response\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/song/update\x12^\n" +
	"\aGetSong\x12\x1c.zpotify_api.GetSong.Request\x1a\x1d.zpotify_api.GetSong.Response\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/song/{id}\x12o\n" +
	"\vSearchSongs\x12 .zpotify_api.SearchSongs.Request\x1a!.zpotify_api.SearchSongs.Response\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/song/searchB*\x92\x82\x19\f@zpotify/apiZ\x18/zpotify_api;zpotify_apib\x06proto3"

var (
	file_zpotify_service_song_proto_rawDescOnce sync.Once
	file_zpotify_service_song_proto_rawDescData []byte
)

func file_zpotify_service_song_proto_rawDescGZIP() []byte {
	file_zpotify_service_song_proto_rawDescOnce.Do(func() {
		file_zpotify_service_song_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zpotify_service_song_proto_rawDesc), len(file_zpotify_service_song_proto_rawDesc)))
	})
	return file_zpotify_service_song_proto_rawDescData
}

var file_zpotify_service_song_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_zpotify_service_song_proto_goTypes = []any{
	(*CreateSong)(nil),               // 0: zpotify_api.CreateSong
	(*BatchCreateSong)(nil),          // 1: zpotify_api.BatchCreateSong
	(*UpdateSong)(nil),               // 2: zpotify_api.UpdateSong
	(*GetSong)(nil),                  // 3: zpotify_api.GetSong
	(*SearchSongs)(nil),              // 4: zpotify_api.SearchSongs
	(*CreateSong_Request)(nil),       // 5: zpotify_api.CreateSong.Request
	(*CreateSong_Response)(nil),      // 6: zpotify_api.CreateSong.Response
	(*BatchCreateSong_Request)(nil),  // 7: zpotify_api.BatchCreateSong.Request
	(*BatchCreateSong_Response)(nil), // 8: zpotify_api.BatchCreateSong.Response
	(*UpdateSong_Request)(nil),       // 9: zpotify_api.UpdateSong.Request
	(*UpdateSong_Response)(nil),      // 10: zpotify_api.UpdateSong.Response
	(*GetSong_Request)(nil),          // 11: zpotify_api.GetSong.Request
	(*GetSong_Response)(nil),         // 12: zpotify_api.GetSong.Response
	(*SearchSongs_Request)(nil),      // 13: zpotify_api.SearchSongs.Request
	(*SearchSongs_Response)(nil),     // 14: zpotify_api.SearchSongs.Response
	(*SongBase)(nil),                 // 15: zpotify_api.SongBase
	(*Paging)(nil),                   // 16: zpotify_api.Paging
}
var file_zpotify_service_song_proto_depIdxs = []int32{
	5,  // 0: zpotify_api.BatchCreateSong.Request.songs:type_name -> zpotify_api.CreateSong.Request
	15, // 1: zpotify_api.GetSong.Response.song:type_name -> zpotify_api.SongBase
	16, // 2: zpotify_api.SearchSongs.Request.paging:type_name -> zpotify_api.Paging
	15, // 3: zpotify_api.SearchSongs.Response.songs:type_name -> zpotify_api.SongBase
	5,  // 4: zpotify_api.SongAPI.CreateSong:input_type -> zpotify_api.CreateSong.Request
	7,  // 5: zpotify_api.SongAPI.BatchCreateSong:input_type -> zpotify_api.BatchCreateSong.Request
	9,  // 6: zpotify_api.SongAPI.UpdateSong:input_type -> zpotify_api.UpdateSong.Request
	11, // 7: zpotify_api.SongAPI.GetSong:input_type -> zpotify_api.GetSong.Request
	13, // 8: zpotify_api.SongAPI.SearchSongs:input_type -> zpotify_api.SearchSongs.Request
	6,  // 9: zpotify_api.SongAPI.CreateSong:output_type -> zpotify_api.CreateSong.Response
	8,  // 10: zpotify_api.SongAPI.BatchCreateSong:output_type -> zpotify_api.BatchCreateSong.Response
	10, // 11: zpotify_api.SongAPI.UpdateSong:output_type -> zpotify_api.UpdateSong.Response
	12, // 12: zpotify_api.SongAPI.GetSong:output_type -> zpotify_api.GetSong.Response
	14, // 13: zpotify_api.SongAPI.SearchSongs:output_type -> zpotify_api.SearchSongs.Response
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_zpotify_service_song_proto_init() }
func file_zpotify_service_song_proto_init() {
	if File_zpotify_service_song_proto != nil {
		return
	}
	file_zpotify_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zpotify_service_song_proto_rawDesc), len(file_zpotify_service_song_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zpotify_service_song_proto_goTypes,
		DependencyIndexes: file_zpotify_service_song_proto_depIdxs,
		MessageInfos:      file_zpotify_service_song_proto_msgTypes,
	}.Build()
	File_zpotify_service_song_proto = out.File
	file_zpotify_service_song_proto_goTypes = nil
	file_zpotify_service_song_proto_depIdxs = nil
}
