// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: zpotify_service_user.proto

package zpotify_api

import (
	_ "go.redsock.ru/protoc-gen-npm/npmplugin"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserData) Reset() {
	*x = UserData{}
	mi := &file_zpotify_service_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserData) ProtoMessage() {}

func (x *UserData) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserData.ProtoReflect.Descriptor instead.
func (*UserData) Descriptor() ([]byte, []int) {
	return file_zpotify_service_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type Me struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Me) Reset() {
	*x = Me{}
	mi := &file_zpotify_service_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Me) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Me) ProtoMessage() {}

func (x *Me) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Me.ProtoReflect.Descriptor instead.
func (*Me) Descriptor() ([]byte, []int) {
	return file_zpotify_service_user_proto_rawDescGZIP(), []int{1}
}

type GetUserSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSettings) Reset() {
	*x = GetUserSettings{}
	mi := &file_zpotify_service_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSettings) ProtoMessage() {}

func (x *GetUserSettings) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSettings.ProtoReflect.Descriptor instead.
func (*GetUserSettings) Descriptor() ([]byte, []int) {
	return file_zpotify_service_user_proto_rawDescGZIP(), []int{2}
}

type Me_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Me_Request) Reset() {
	*x = Me_Request{}
	mi := &file_zpotify_service_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Me_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Me_Request) ProtoMessage() {}

func (x *Me_Request) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Me_Request.ProtoReflect.Descriptor instead.
func (*Me_Request) Descriptor() ([]byte, []int) {
	return file_zpotify_service_user_proto_rawDescGZIP(), []int{1, 0}
}

type Me_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserData      *UserData              `protobuf:"bytes,1,opt,name=user_data,json=userData,proto3" json:"user_data,omitempty"`
	Permissions   *Permissions           `protobuf:"bytes,2,opt,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Me_Response) Reset() {
	*x = Me_Response{}
	mi := &file_zpotify_service_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Me_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Me_Response) ProtoMessage() {}

func (x *Me_Response) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Me_Response.ProtoReflect.Descriptor instead.
func (*Me_Response) Descriptor() ([]byte, []int) {
	return file_zpotify_service_user_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Me_Response) GetUserData() *UserData {
	if x != nil {
		return x.UserData
	}
	return nil
}

func (x *Me_Response) GetPermissions() *Permissions {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type GetUserSettings_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSettings_Request) Reset() {
	*x = GetUserSettings_Request{}
	mi := &file_zpotify_service_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSettings_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSettings_Request) ProtoMessage() {}

func (x *GetUserSettings_Request) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSettings_Request.ProtoReflect.Descriptor instead.
func (*GetUserSettings_Request) Descriptor() ([]byte, []int) {
	return file_zpotify_service_user_proto_rawDescGZIP(), []int{2, 0}
}

type GetUserSettings_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *UserSettings          `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSettings_Response) Reset() {
	*x = GetUserSettings_Response{}
	mi := &file_zpotify_service_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSettings_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSettings_Response) ProtoMessage() {}

func (x *GetUserSettings_Response) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSettings_Response.ProtoReflect.Descriptor instead.
func (*GetUserSettings_Response) Descriptor() ([]byte, []int) {
	return file_zpotify_service_user_proto_rawDescGZIP(), []int{2, 1}
}

func (x *GetUserSettings_Response) GetSettings() *UserSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

var File_zpotify_service_user_proto protoreflect.FileDescriptor

const file_zpotify_service_user_proto_rawDesc = "" +
	"\n" +
	"\x1azpotify_service_user.proto\x12\vzpotify_api\x1a\tnpm.proto\x1a\x12zpotify_user.proto\x1a\x1bzpotify_user_settings.proto\x1a\x1cgoogle/api/annotations.proto\"&\n" +
	"\bUserData\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"\x8b\x01\n" +
	"\x02Me\x1a\t\n" +
	"\aRequest\x1az\n" +
	"\bResponse\x122\n" +
	"\tuser_data\x18\x01 \x01(\v2\x15.zpotify_api.UserDataR\buserData\x12:\n" +
	"\vpermissions\x18\x02 \x01(\v2\x18.zpotify_api.PermissionsR\vpermissions\"_\n" +
	"\x0fGetUserSettings\x1a\t\n" +
	"\aRequest\x1aA\n" +
	"\bResponse\x125\n" +
	"\bsettings\x18\x01 \x01(\v2\x19.zpotify_api.UserSettingsR\bsettings2\xd4\x01\n" +
	"\aUserAPI\x12M\n" +
	"\x02Me\x12\x17.zpotify_api.Me.Request\x1a\x18.zpotify_api.Me.Response\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/api/user/me\x12z\n" +
	"\x0fGetUserSettings\x12$.zpotify_api.GetUserSettings.Request\x1a%.zpotify_api.GetUserSettings.Response\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/user/settingsB*\x92\x82\x19\f@zpotify/apiZ\x18/zpotify_api;zpotify_apib\x06proto3"

var (
	file_zpotify_service_user_proto_rawDescOnce sync.Once
	file_zpotify_service_user_proto_rawDescData []byte
)

func file_zpotify_service_user_proto_rawDescGZIP() []byte {
	file_zpotify_service_user_proto_rawDescOnce.Do(func() {
		file_zpotify_service_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zpotify_service_user_proto_rawDesc), len(file_zpotify_service_user_proto_rawDesc)))
	})
	return file_zpotify_service_user_proto_rawDescData
}

var file_zpotify_service_user_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_zpotify_service_user_proto_goTypes = []any{
	(*UserData)(nil),                 // 0: zpotify_api.UserData
	(*Me)(nil),                       // 1: zpotify_api.Me
	(*GetUserSettings)(nil),          // 2: zpotify_api.GetUserSettings
	(*Me_Request)(nil),               // 3: zpotify_api.Me.Request
	(*Me_Response)(nil),              // 4: zpotify_api.Me.Response
	(*GetUserSettings_Request)(nil),  // 5: zpotify_api.GetUserSettings.Request
	(*GetUserSettings_Response)(nil), // 6: zpotify_api.GetUserSettings.Response
	(*Permissions)(nil),              // 7: zpotify_api.Permissions
	(*UserSettings)(nil),             // 8: zpotify_api.UserSettings
}
var file_zpotify_service_user_proto_depIdxs = []int32{
	0, // 0: zpotify_api.Me.Response.user_data:type_name -> zpotify_api.UserData
	7, // 1: zpotify_api.Me.Response.permissions:type_name -> zpotify_api.Permissions
	8, // 2: zpotify_api.GetUserSettings.Response.settings:type_name -> zpotify_api.UserSettings
	3, // 3: zpotify_api.UserAPI.Me:input_type -> zpotify_api.Me.Request
	5, // 4: zpotify_api.UserAPI.GetUserSettings:input_type -> zpotify_api.GetUserSettings.Request
	4, // 5: zpotify_api.UserAPI.Me:output_type -> zpotify_api.Me.Response
	6, // 6: zpotify_api.UserAPI.GetUserSettings:output_type -> zpotify_api.GetUserSettings.Response
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_zpotify_service_user_proto_init() }
func file_zpotify_service_user_proto_init() {
	if File_zpotify_service_user_proto != nil {
		return
	}
	file_zpotify_user_proto_init()
	file_zpotify_user_settings_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zpotify_service_user_proto_rawDesc), len(file_zpotify_service_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zpotify_service_user_proto_goTypes,
		DependencyIndexes: file_zpotify_service_user_proto_depIdxs,
		MessageInfos:      file_zpotify_service_user_proto_msgTypes,
	}.Build()
	File_zpotify_service_user_proto = out.File
	file_zpotify_service_user_proto_goTypes = nil
	file_zpotify_service_user_proto_depIdxs = nil
}
