// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: zpotify_service_feature_flags.proto

package zpotify_api

import (
	_ "go.redsock.ru/protoc-gen-npm/npmplugin"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeatureFlagId int32

const (
	FeatureFlagId_FEATURE_FLAG_ID_UNSPECIFIED  FeatureFlagId = 0
	FeatureFlagId_IS_COMMENTS_ON_ALBUM_ENABLED FeatureFlagId = 1
)

// Enum value maps for FeatureFlagId.
var (
	FeatureFlagId_name = map[int32]string{
		0: "FEATURE_FLAG_ID_UNSPECIFIED",
		1: "IS_COMMENTS_ON_ALBUM_ENABLED",
	}
	FeatureFlagId_value = map[string]int32{
		"FEATURE_FLAG_ID_UNSPECIFIED":  0,
		"IS_COMMENTS_ON_ALBUM_ENABLED": 1,
	}
)

func (x FeatureFlagId) Enum() *FeatureFlagId {
	p := new(FeatureFlagId)
	*p = x
	return p
}

func (x FeatureFlagId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FeatureFlagId) Descriptor() protoreflect.EnumDescriptor {
	return file_zpotify_service_feature_flags_proto_enumTypes[0].Descriptor()
}

func (FeatureFlagId) Type() protoreflect.EnumType {
	return &file_zpotify_service_feature_flags_proto_enumTypes[0]
}

func (x FeatureFlagId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FeatureFlagId.Descriptor instead.
func (FeatureFlagId) EnumDescriptor() ([]byte, []int) {
	return file_zpotify_service_feature_flags_proto_rawDescGZIP(), []int{0}
}

type FeatureFlag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            FeatureFlagId          `protobuf:"varint,1,opt,name=id,proto3,enum=zpotify_api.FeatureFlagId" json:"id,omitempty"`
	IsEnabled     bool                   `protobuf:"varint,2,opt,name=is_enabled,json=isEnabled,proto3" json:"is_enabled,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureFlag) Reset() {
	*x = FeatureFlag{}
	mi := &file_zpotify_service_feature_flags_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureFlag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureFlag) ProtoMessage() {}

func (x *FeatureFlag) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_feature_flags_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureFlag.ProtoReflect.Descriptor instead.
func (*FeatureFlag) Descriptor() ([]byte, []int) {
	return file_zpotify_service_feature_flags_proto_rawDescGZIP(), []int{0}
}

func (x *FeatureFlag) GetId() FeatureFlagId {
	if x != nil {
		return x.Id
	}
	return FeatureFlagId_FEATURE_FLAG_ID_UNSPECIFIED
}

func (x *FeatureFlag) GetIsEnabled() bool {
	if x != nil {
		return x.IsEnabled
	}
	return false
}

func (x *FeatureFlag) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetFeatureFlags struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeatureFlags) Reset() {
	*x = GetFeatureFlags{}
	mi := &file_zpotify_service_feature_flags_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeatureFlags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeatureFlags) ProtoMessage() {}

func (x *GetFeatureFlags) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_feature_flags_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeatureFlags.ProtoReflect.Descriptor instead.
func (*GetFeatureFlags) Descriptor() ([]byte, []int) {
	return file_zpotify_service_feature_flags_proto_rawDescGZIP(), []int{1}
}

type GetFeatureFlags_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeatureFlags_Request) Reset() {
	*x = GetFeatureFlags_Request{}
	mi := &file_zpotify_service_feature_flags_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeatureFlags_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeatureFlags_Request) ProtoMessage() {}

func (x *GetFeatureFlags_Request) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_feature_flags_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeatureFlags_Request.ProtoReflect.Descriptor instead.
func (*GetFeatureFlags_Request) Descriptor() ([]byte, []int) {
	return file_zpotify_service_feature_flags_proto_rawDescGZIP(), []int{1, 0}
}

type GetFeatureFlags_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flags         []*FeatureFlag         `protobuf:"bytes,1,rep,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeatureFlags_Response) Reset() {
	*x = GetFeatureFlags_Response{}
	mi := &file_zpotify_service_feature_flags_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeatureFlags_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeatureFlags_Response) ProtoMessage() {}

func (x *GetFeatureFlags_Response) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_feature_flags_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeatureFlags_Response.ProtoReflect.Descriptor instead.
func (*GetFeatureFlags_Response) Descriptor() ([]byte, []int) {
	return file_zpotify_service_feature_flags_proto_rawDescGZIP(), []int{1, 1}
}

func (x *GetFeatureFlags_Response) GetFlags() []*FeatureFlag {
	if x != nil {
		return x.Flags
	}
	return nil
}

var File_zpotify_service_feature_flags_proto protoreflect.FileDescriptor

const file_zpotify_service_feature_flags_proto_rawDesc = "" +
	"\n" +
	"#zpotify_service_feature_flags.proto\x12\vzpotify_api\x1a\tnpm.proto\x1a\x1cgoogle/api/annotations.proto\"n\n" +
	"\vFeatureFlag\x12*\n" +
	"\x02id\x18\x01 \x01(\x0e2\x1a.zpotify_api.FeatureFlagIdR\x02id\x12\x1d\n" +
	"\n" +
	"is_enabled\x18\x02 \x01(\bR\tisEnabled\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"X\n" +
	"\x0fGetFeatureFlags\x1a\t\n" +
	"\aRequest\x1a:\n" +
	"\bResponse\x12.\n" +
	"\x05flags\x18\x01 \x03(\v2\x18.zpotify_api.FeatureFlagR\x05flags*R\n" +
	"\rFeatureFlagId\x12\x1f\n" +
	"\x1bFEATURE_FLAG_ID_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cIS_COMMENTS_ON_ALBUM_ENABLED\x10\x012\x8d\x01\n" +
	"\x0fFeatureFlagsAPI\x12z\n" +
	"\x0fGetFeatureFlags\x12$.zpotify_api.GetFeatureFlags.Request\x1a%.zpotify_api.GetFeatureFlags.Response\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/feature-flagsB*\x92\x82\x19\f@zpotify/apiZ\x18/zpotify_api;zpotify_apib\x06proto3"

var (
	file_zpotify_service_feature_flags_proto_rawDescOnce sync.Once
	file_zpotify_service_feature_flags_proto_rawDescData []byte
)

func file_zpotify_service_feature_flags_proto_rawDescGZIP() []byte {
	file_zpotify_service_feature_flags_proto_rawDescOnce.Do(func() {
		file_zpotify_service_feature_flags_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zpotify_service_feature_flags_proto_rawDesc), len(file_zpotify_service_feature_flags_proto_rawDesc)))
	})
	return file_zpotify_service_feature_flags_proto_rawDescData
}

var file_zpotify_service_feature_flags_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_zpotify_service_feature_flags_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_zpotify_service_feature_flags_proto_goTypes = []any{
	(FeatureFlagId)(0),               // 0: zpotify_api.FeatureFlagId
	(*FeatureFlag)(nil),              // 1: zpotify_api.FeatureFlag
	(*GetFeatureFlags)(nil),          // 2: zpotify_api.GetFeatureFlags
	(*GetFeatureFlags_Request)(nil),  // 3: zpotify_api.GetFeatureFlags.Request
	(*GetFeatureFlags_Response)(nil), // 4: zpotify_api.GetFeatureFlags.Response
}
var file_zpotify_service_feature_flags_proto_depIdxs = []int32{
	0, // 0: zpotify_api.FeatureFlag.id:type_name -> zpotify_api.FeatureFlagId
	1, // 1: zpotify_api.GetFeatureFlags.Response.flags:type_name -> zpotify_api.FeatureFlag
	3, // 2: zpotify_api.FeatureFlagsAPI.GetFeatureFlags:input_type -> zpotify_api.GetFeatureFlags.Request
	4, // 3: zpotify_api.FeatureFlagsAPI.GetFeatureFlags:output_type -> zpotify_api.GetFeatureFlags.Response
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_zpotify_service_feature_flags_proto_init() }
func file_zpotify_service_feature_flags_proto_init() {
	if File_zpotify_service_feature_flags_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zpotify_service_feature_flags_proto_rawDesc), len(file_zpotify_service_feature_flags_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zpotify_service_feature_flags_proto_goTypes,
		DependencyIndexes: file_zpotify_service_feature_flags_proto_depIdxs,
		EnumInfos:         file_zpotify_service_feature_flags_proto_enumTypes,
		MessageInfos:      file_zpotify_service_feature_flags_proto_msgTypes,
	}.Build()
	File_zpotify_service_feature_flags_proto = out.File
	file_zpotify_service_feature_flags_proto_goTypes = nil
	file_zpotify_service_feature_flags_proto_depIdxs = nil
}
