// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: zpotify_service_search.proto

package zpotify_api

import (
	_ "go.redsock.ru/protoc-gen-npm/npmplugin"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Search struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Search) Reset() {
	*x = Search{}
	mi := &file_zpotify_service_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Search) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Search) ProtoMessage() {}

func (x *Search) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Search.ProtoReflect.Descriptor instead.
func (*Search) Descriptor() ([]byte, []int) {
	return file_zpotify_service_search_proto_rawDescGZIP(), []int{0}
}

type SearchFilters struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reserved for future genre/mood facet chips (reuses AlbumTag kinds). Unused server-side in v1 — accepted but ignored.
	Tags          []string `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchFilters) Reset() {
	*x = SearchFilters{}
	mi := &file_zpotify_service_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFilters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFilters) ProtoMessage() {}

func (x *SearchFilters) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFilters.ProtoReflect.Descriptor instead.
func (*SearchFilters) Descriptor() ([]byte, []int) {
	return file_zpotify_service_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchFilters) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Search_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Paging        *Paging                `protobuf:"bytes,2,opt,name=paging,proto3" json:"paging,omitempty"`
	Filters       *SearchFilters         `protobuf:"bytes,3,opt,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Search_Request) Reset() {
	*x = Search_Request{}
	mi := &file_zpotify_service_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Search_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Search_Request) ProtoMessage() {}

func (x *Search_Request) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Search_Request.ProtoReflect.Descriptor instead.
func (*Search_Request) Descriptor() ([]byte, []int) {
	return file_zpotify_service_search_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Search_Request) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *Search_Request) GetPaging() *Paging {
	if x != nil {
		return x.Paging
	}
	return nil
}

func (x *Search_Request) GetFilters() *SearchFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

type Search_Response struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Tracks        []*Search_TrackResult    `protobuf:"bytes,1,rep,name=tracks,proto3" json:"tracks,omitempty"`
	Artists       []*Search_ArtistResult   `protobuf:"bytes,2,rep,name=artists,proto3" json:"artists,omitempty"`
	Albums        []*Search_AlbumResult    `protobuf:"bytes,3,rep,name=albums,proto3" json:"albums,omitempty"`
	Playlists     []*Search_PlaylistResult `protobuf:"bytes,4,rep,name=playlists,proto3" json:"playlists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Search_Response) Reset() {
	*x = Search_Response{}
	mi := &file_zpotify_service_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Search_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Search_Response) ProtoMessage() {}

func (x *Search_Response) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Search_Response.ProtoReflect.Descriptor instead.
func (*Search_Response) Descriptor() ([]byte, []int) {
	return file_zpotify_service_search_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Search_Response) GetTracks() []*Search_TrackResult {
	if x != nil {
		return x.Tracks
	}
	return nil
}

func (x *Search_Response) GetArtists() []*Search_ArtistResult {
	if x != nil {
		return x.Artists
	}
	return nil
}

func (x *Search_Response) GetAlbums() []*Search_AlbumResult {
	if x != nil {
		return x.Albums
	}
	return nil
}

func (x *Search_Response) GetPlaylists() []*Search_PlaylistResult {
	if x != nil {
		return x.Playlists
	}
	return nil
}

type Search_TrackResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Song          *SongBase              `protobuf:"bytes,1,opt,name=song,proto3" json:"song,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Search_TrackResult) Reset() {
	*x = Search_TrackResult{}
	mi := &file_zpotify_service_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Search_TrackResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Search_TrackResult) ProtoMessage() {}

func (x *Search_TrackResult) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Search_TrackResult.ProtoReflect.Descriptor instead.
func (*Search_TrackResult) Descriptor() ([]byte, []int) {
	return file_zpotify_service_search_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Search_TrackResult) GetSong() *SongBase {
	if x != nil {
		return x.Song
	}
	return nil
}

func (x *Search_TrackResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type Search_ArtistResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artist        *ArtistBase            `protobuf:"bytes,1,opt,name=artist,proto3" json:"artist,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Search_ArtistResult) Reset() {
	*x = Search_ArtistResult{}
	mi := &file_zpotify_service_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Search_ArtistResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Search_ArtistResult) ProtoMessage() {}

func (x *Search_ArtistResult) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Search_ArtistResult.ProtoReflect.Descriptor instead.
func (*Search_ArtistResult) Descriptor() ([]byte, []int) {
	return file_zpotify_service_search_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Search_ArtistResult) GetArtist() *ArtistBase {
	if x != nil {
		return x.Artist
	}
	return nil
}

func (x *Search_ArtistResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type Search_AlbumResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Playlist      *Playlist              `protobuf:"bytes,1,opt,name=playlist,proto3" json:"playlist,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Search_AlbumResult) Reset() {
	*x = Search_AlbumResult{}
	mi := &file_zpotify_service_search_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Search_AlbumResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Search_AlbumResult) ProtoMessage() {}

func (x *Search_AlbumResult) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_search_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Search_AlbumResult.ProtoReflect.Descriptor instead.
func (*Search_AlbumResult) Descriptor() ([]byte, []int) {
	return file_zpotify_service_search_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Search_AlbumResult) GetPlaylist() *Playlist {
	if x != nil {
		return x.Playlist
	}
	return nil
}

func (x *Search_AlbumResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type Search_PlaylistResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Playlist      *Playlist              `protobuf:"bytes,1,opt,name=playlist,proto3" json:"playlist,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Search_PlaylistResult) Reset() {
	*x = Search_PlaylistResult{}
	mi := &file_zpotify_service_search_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Search_PlaylistResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Search_PlaylistResult) ProtoMessage() {}

func (x *Search_PlaylistResult) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_search_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Search_PlaylistResult.ProtoReflect.Descriptor instead.
func (*Search_PlaylistResult) Descriptor() ([]byte, []int) {
	return file_zpotify_service_search_proto_rawDescGZIP(), []int{0, 5}
}

func (x *Search_PlaylistResult) GetPlaylist() *Playlist {
	if x != nil {
		return x.Playlist
	}
	return nil
}

func (x *Search_PlaylistResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_zpotify_service_search_proto protoreflect.FileDescriptor

const file_zpotify_service_search_proto_rawDesc = "" +
	"\n" +
	"\x1czpotify_service_search.proto\x12\vzpotify_api\x1a\x1cgoogle/api/annotations.proto\x1a\tnpm.proto\x1a\x14zpotify_common.proto\"\xe4\x05\n" +
	"\x06Search\x1a\x82\x01\n" +
	"\aRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12+\n" +
	"\x06paging\x18\x02 \x01(\v2\x13.zpotify_api.PagingR\x06paging\x124\n" +
	"\afilters\x18\x03 \x01(\v2\x1a.zpotify_api.SearchFiltersR\afilters\x1a\xfa\x01\n" +
	"\bResponse\x127\n" +
	"\x06tracks\x18\x01 \x03(\v2\x1f.zpotify_api.Search.TrackResultR\x06tracks\x12:\n" +
	"\aartists\x18\x02 \x03(\v2 .zpotify_api.Search.ArtistResultR\aartists\x127\n" +
	"\x06albums\x18\x03 \x03(\v2\x1f.zpotify_api.Search.AlbumResultR\x06albums\x12@\n" +
	"\tplaylists\x18\x04 \x03(\v2\".zpotify_api.Search.PlaylistResultR\tplaylists\x1aN\n" +
	"\vTrackResult\x12)\n" +
	"\x04song\x18\x01 \x01(\v2\x15.zpotify_api.SongBaseR\x04song\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x1aU\n" +
	"\fArtistResult\x12/\n" +
	"\x06artist\x18\x01 \x01(\v2\x17.zpotify_api.ArtistBaseR\x06artist\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x1aV\n" +
	"\vAlbumResult\x121\n" +
	"\bplaylist\x18\x01 \x01(\v2\x15.zpotify_api.PlaylistR\bplaylist\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x1aY\n" +
	"\x0ePlaylistResult\x121\n" +
	"\bplaylist\x18\x01 \x01(\v2\x15.zpotify_api.PlaylistR\bplaylist\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\"#\n" +
	"\rSearchFilters\x12\x12\n" +
	"\x04tags\x18\x01 \x03(\tR\x04tags2h\n" +
	"\tSearchAPI\x12[\n" +
	"\x06Search\x12\x1b.zpotify_api.Search.Request\x1a\x1c.zpotify_api.Search.Response\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/api/searchBA\x92\x82\x19\f@zpotify/api\n" +
	"\x13ru.zpotify.api.grpcP\x01Z\x18/zpotify_api;zpotify_apib\x06proto3"

var (
	file_zpotify_service_search_proto_rawDescOnce sync.Once
	file_zpotify_service_search_proto_rawDescData []byte
)

func file_zpotify_service_search_proto_rawDescGZIP() []byte {
	file_zpotify_service_search_proto_rawDescOnce.Do(func() {
		file_zpotify_service_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zpotify_service_search_proto_rawDesc), len(file_zpotify_service_search_proto_rawDesc)))
	})
	return file_zpotify_service_search_proto_rawDescData
}

var file_zpotify_service_search_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_zpotify_service_search_proto_goTypes = []any{
	(*Search)(nil),                // 0: zpotify_api.Search
	(*SearchFilters)(nil),         // 1: zpotify_api.SearchFilters
	(*Search_Request)(nil),        // 2: zpotify_api.Search.Request
	(*Search_Response)(nil),       // 3: zpotify_api.Search.Response
	(*Search_TrackResult)(nil),    // 4: zpotify_api.Search.TrackResult
	(*Search_ArtistResult)(nil),   // 5: zpotify_api.Search.ArtistResult
	(*Search_AlbumResult)(nil),    // 6: zpotify_api.Search.AlbumResult
	(*Search_PlaylistResult)(nil), // 7: zpotify_api.Search.PlaylistResult
	(*Paging)(nil),                // 8: zpotify_api.Paging
	(*SongBase)(nil),              // 9: zpotify_api.SongBase
	(*ArtistBase)(nil),            // 10: zpotify_api.ArtistBase
	(*Playlist)(nil),              // 11: zpotify_api.Playlist
}
var file_zpotify_service_search_proto_depIdxs = []int32{
	8,  // 0: zpotify_api.Search.Request.paging:type_name -> zpotify_api.Paging
	1,  // 1: zpotify_api.Search.Request.filters:type_name -> zpotify_api.SearchFilters
	4,  // 2: zpotify_api.Search.Response.tracks:type_name -> zpotify_api.Search.TrackResult
	5,  // 3: zpotify_api.Search.Response.artists:type_name -> zpotify_api.Search.ArtistResult
	6,  // 4: zpotify_api.Search.Response.albums:type_name -> zpotify_api.Search.AlbumResult
	7,  // 5: zpotify_api.Search.Response.playlists:type_name -> zpotify_api.Search.PlaylistResult
	9,  // 6: zpotify_api.Search.TrackResult.song:type_name -> zpotify_api.SongBase
	10, // 7: zpotify_api.Search.ArtistResult.artist:type_name -> zpotify_api.ArtistBase
	11, // 8: zpotify_api.Search.AlbumResult.playlist:type_name -> zpotify_api.Playlist
	11, // 9: zpotify_api.Search.PlaylistResult.playlist:type_name -> zpotify_api.Playlist
	2,  // 10: zpotify_api.SearchAPI.Search:input_type -> zpotify_api.Search.Request
	3,  // 11: zpotify_api.SearchAPI.Search:output_type -> zpotify_api.Search.Response
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_zpotify_service_search_proto_init() }
func file_zpotify_service_search_proto_init() {
	if File_zpotify_service_search_proto != nil {
		return
	}
	file_zpotify_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zpotify_service_search_proto_rawDesc), len(file_zpotify_service_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zpotify_service_search_proto_goTypes,
		DependencyIndexes: file_zpotify_service_search_proto_depIdxs,
		MessageInfos:      file_zpotify_service_search_proto_msgTypes,
	}.Build()
	File_zpotify_service_search_proto = out.File
	file_zpotify_service_search_proto_goTypes = nil
	file_zpotify_service_search_proto_depIdxs = nil
}
