// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: zpotify_service_file.proto

package zpotify_api

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// FileAPIClient is the client API for FileAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileAPIClient interface {
}

type fileAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewFileAPIClient(cc grpc.ClientConnInterface) FileAPIClient {
	return &fileAPIClient{cc}
}

// FileAPIServer is the server API for FileAPI service.
// All implementations must embed UnimplementedFileAPIServer
// for forward compatibility.
type FileAPIServer interface {
	mustEmbedUnimplementedFileAPIServer()
}

// UnimplementedFileAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileAPIServer struct{}

func (UnimplementedFileAPIServer) mustEmbedUnimplementedFileAPIServer() {}
func (UnimplementedFileAPIServer) testEmbeddedByValue()                 {}

// UnsafeFileAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileAPIServer will
// result in compilation errors.
type UnsafeFileAPIServer interface {
	mustEmbedUnimplementedFileAPIServer()
}

func RegisterFileAPIServer(s grpc.ServiceRegistrar, srv FileAPIServer) {
	// If the following call panics, it indicates UnimplementedFileAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileAPI_ServiceDesc, srv)
}

// FileAPI_ServiceDesc is the grpc.ServiceDesc for FileAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zpotify_api.FileAPI",
	HandlerType: (*FileAPIServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "zpotify_service_file.proto",
}
