// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: zpotify_auth_service.proto

package zpotify_api

import (
	_ "go.redsock.ru/protoc-gen-npm/npmplugin"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAuthMethods struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthMethods) Reset() {
	*x = GetAuthMethods{}
	mi := &file_zpotify_auth_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthMethods) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthMethods) ProtoMessage() {}

func (x *GetAuthMethods) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_auth_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthMethods.ProtoReflect.Descriptor instead.
func (*GetAuthMethods) Descriptor() ([]byte, []int) {
	return file_zpotify_auth_service_proto_rawDescGZIP(), []int{0}
}

type AuthViaAsync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthViaAsync) Reset() {
	*x = AuthViaAsync{}
	mi := &file_zpotify_auth_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthViaAsync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthViaAsync) ProtoMessage() {}

func (x *AuthViaAsync) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_auth_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthViaAsync.ProtoReflect.Descriptor instead.
func (*AuthViaAsync) Descriptor() ([]byte, []int) {
	return file_zpotify_auth_service_proto_rawDescGZIP(), []int{1}
}

type Auth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_zpotify_auth_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_auth_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_zpotify_auth_service_proto_rawDescGZIP(), []int{2}
}

type Refresh struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Refresh) Reset() {
	*x = Refresh{}
	mi := &file_zpotify_auth_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Refresh) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Refresh) ProtoMessage() {}

func (x *Refresh) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_auth_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Refresh.ProtoReflect.Descriptor instead.
func (*Refresh) Descriptor() ([]byte, []int) {
	return file_zpotify_auth_service_proto_rawDescGZIP(), []int{3}
}

type AuthData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccessToken      string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken     string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	AccessExpiresAt  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=access_expires_at,json=accessExpiresAt,proto3" json:"access_expires_at,omitempty"`
	RefreshExpiresAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=refresh_expires_at,json=refreshExpiresAt,proto3" json:"refresh_expires_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuthData) Reset() {
	*x = AuthData{}
	mi := &file_zpotify_auth_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthData) ProtoMessage() {}

func (x *AuthData) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_auth_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthData.ProtoReflect.Descriptor instead.
func (*AuthData) Descriptor() ([]byte, []int) {
	return file_zpotify_auth_service_proto_rawDescGZIP(), []int{4}
}

func (x *AuthData) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AuthData) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *AuthData) GetAccessExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AccessExpiresAt
	}
	return nil
}

func (x *AuthData) GetRefreshExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RefreshExpiresAt
	}
	return nil
}

type GetAuthMethods_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthMethods_Request) Reset() {
	*x = GetAuthMethods_Request{}
	mi := &file_zpotify_auth_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthMethods_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthMethods_Request) ProtoMessage() {}

func (x *GetAuthMethods_Request) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_auth_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthMethods_Request.ProtoReflect.Descriptor instead.
func (*GetAuthMethods_Request) Descriptor() ([]byte, []int) {
	return file_zpotify_auth_service_proto_rawDescGZIP(), []int{0, 0}
}

type GetAuthMethods_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthMethods   []AuthMethods          `protobuf:"varint,1,rep,packed,name=auth_methods,json=authMethods,proto3,enum=zpotify_api.AuthMethods" json:"auth_methods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthMethods_Response) Reset() {
	*x = GetAuthMethods_Response{}
	mi := &file_zpotify_auth_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthMethods_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthMethods_Response) ProtoMessage() {}

func (x *GetAuthMethods_Response) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_auth_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthMethods_Response.ProtoReflect.Descriptor instead.
func (*GetAuthMethods_Response) Descriptor() ([]byte, []int) {
	return file_zpotify_auth_service_proto_rawDescGZIP(), []int{0, 1}
}

func (x *GetAuthMethods_Response) GetAuthMethods() []AuthMethods {
	if x != nil {
		return x.AuthMethods
	}
	return nil
}

type AuthViaAsync_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthViaAsync_Request) Reset() {
	*x = AuthViaAsync_Request{}
	mi := &file_zpotify_auth_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthViaAsync_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthViaAsync_Request) ProtoMessage() {}

func (x *AuthViaAsync_Request) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_auth_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthViaAsync_Request.ProtoReflect.Descriptor instead.
func (*AuthViaAsync_Request) Descriptor() ([]byte, []int) {
	return file_zpotify_auth_service_proto_rawDescGZIP(), []int{1, 0}
}

type AuthViaAsync_Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AuthViaAsync_Response_AuthUuid
	//	*AuthViaAsync_Response_AuthData
	Payload       isAuthViaAsync_Response_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthViaAsync_Response) Reset() {
	*x = AuthViaAsync_Response{}
	mi := &file_zpotify_auth_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthViaAsync_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthViaAsync_Response) ProtoMessage() {}

func (x *AuthViaAsync_Response) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_auth_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthViaAsync_Response.ProtoReflect.Descriptor instead.
func (*AuthViaAsync_Response) Descriptor() ([]byte, []int) {
	return file_zpotify_auth_service_proto_rawDescGZIP(), []int{1, 1}
}

func (x *AuthViaAsync_Response) GetPayload() isAuthViaAsync_Response_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AuthViaAsync_Response) GetAuthUuid() string {
	if x != nil {
		if x, ok := x.Payload.(*AuthViaAsync_Response_AuthUuid); ok {
			return x.AuthUuid
		}
	}
	return ""
}

func (x *AuthViaAsync_Response) GetAuthData() *AuthData {
	if x != nil {
		if x, ok := x.Payload.(*AuthViaAsync_Response_AuthData); ok {
			return x.AuthData
		}
	}
	return nil
}

type isAuthViaAsync_Response_Payload interface {
	isAuthViaAsync_Response_Payload()
}

type AuthViaAsync_Response_AuthUuid struct {
	AuthUuid string `protobuf:"bytes,1,opt,name=auth_uuid,json=authUuid,proto3,oneof"`
}

type AuthViaAsync_Response_AuthData struct {
	AuthData *AuthData `protobuf:"bytes,2,opt,name=auth_data,json=authData,proto3,oneof"`
}

func (*AuthViaAsync_Response_AuthUuid) isAuthViaAsync_Response_Payload() {}

func (*AuthViaAsync_Response_AuthData) isAuthViaAsync_Response_Payload() {}

type Auth_Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Auth_Request_LogPass
	Payload       isAuth_Request_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auth_Request) Reset() {
	*x = Auth_Request{}
	mi := &file_zpotify_auth_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth_Request) ProtoMessage() {}

func (x *Auth_Request) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_auth_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth_Request.ProtoReflect.Descriptor instead.
func (*Auth_Request) Descriptor() ([]byte, []int) {
	return file_zpotify_auth_service_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Auth_Request) GetPayload() isAuth_Request_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Auth_Request) GetLogPass() *Auth_LogPass {
	if x != nil {
		if x, ok := x.Payload.(*Auth_Request_LogPass); ok {
			return x.LogPass
		}
	}
	return nil
}

type isAuth_Request_Payload interface {
	isAuth_Request_Payload()
}

type Auth_Request_LogPass struct {
	LogPass *Auth_LogPass `protobuf:"bytes,1,opt,name=log_pass,json=logPass,proto3,oneof"`
}

func (*Auth_Request_LogPass) isAuth_Request_Payload() {}

type Auth_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthData      *AuthData              `protobuf:"bytes,1,opt,name=auth_data,json=authData,proto3" json:"auth_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auth_Response) Reset() {
	*x = Auth_Response{}
	mi := &file_zpotify_auth_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth_Response) ProtoMessage() {}

func (x *Auth_Response) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_auth_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth_Response.ProtoReflect.Descriptor instead.
func (*Auth_Response) Descriptor() ([]byte, []int) {
	return file_zpotify_auth_service_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Auth_Response) GetAuthData() *AuthData {
	if x != nil {
		return x.AuthData
	}
	return nil
}

type Auth_LogPass struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auth_LogPass) Reset() {
	*x = Auth_LogPass{}
	mi := &file_zpotify_auth_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth_LogPass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth_LogPass) ProtoMessage() {}

func (x *Auth_LogPass) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_auth_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth_LogPass.ProtoReflect.Descriptor instead.
func (*Auth_LogPass) Descriptor() ([]byte, []int) {
	return file_zpotify_auth_service_proto_rawDescGZIP(), []int{2, 2}
}

func (x *Auth_LogPass) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *Auth_LogPass) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Refresh_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Refresh_Request) Reset() {
	*x = Refresh_Request{}
	mi := &file_zpotify_auth_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Refresh_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Refresh_Request) ProtoMessage() {}

func (x *Refresh_Request) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_auth_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Refresh_Request.ProtoReflect.Descriptor instead.
func (*Refresh_Request) Descriptor() ([]byte, []int) {
	return file_zpotify_auth_service_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Refresh_Request) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type Refresh_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthData      *AuthData              `protobuf:"bytes,1,opt,name=auth_data,json=authData,proto3" json:"auth_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Refresh_Response) Reset() {
	*x = Refresh_Response{}
	mi := &file_zpotify_auth_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Refresh_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Refresh_Response) ProtoMessage() {}

func (x *Refresh_Response) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_auth_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Refresh_Response.ProtoReflect.Descriptor instead.
func (*Refresh_Response) Descriptor() ([]byte, []int) {
	return file_zpotify_auth_service_proto_rawDescGZIP(), []int{3, 1}
}

func (x *Refresh_Response) GetAuthData() *AuthData {
	if x != nil {
		return x.AuthData
	}
	return nil
}

var File_zpotify_auth_service_proto protoreflect.FileDescriptor

const file_zpotify_auth_service_proto_rawDesc = "" +
	"\n" +
	"\x1azpotify_auth_service.proto\x12\vzpotify_api\x1a\tnpm.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x14zpotify_common.proto\x1a\x12zpotify_user.proto\"d\n" +
	"\x0eGetAuthMethods\x1a\t\n" +
	"\aRequest\x1aG\n" +
	"\bResponse\x12;\n" +
	"\fauth_methods\x18\x01 \x03(\x0e2\x18.zpotify_api.AuthMethodsR\vauthMethods\"\x85\x01\n" +
	"\fAuthViaAsync\x1a\t\n" +
	"\aRequest\x1aj\n" +
	"\bResponse\x12\x1d\n" +
	"\tauth_uuid\x18\x01 \x01(\tH\x00R\bauthUuid\x124\n" +
	"\tauth_data\x18\x02 \x01(\v2\x15.zpotify_api.AuthDataH\x00R\bauthDataB\t\n" +
	"\apayload\"\xd1\x01\n" +
	"\x04Auth\x1aL\n" +
	"\aRequest\x126\n" +
	"\blog_pass\x18\x01 \x01(\v2\x19.zpotify_api.Auth.LogPassH\x00R\alogPassB\t\n" +
	"\apayload\x1a>\n" +
	"\bResponse\x122\n" +
	"\tauth_data\x18\x01 \x01(\v2\x15.zpotify_api.AuthDataR\bauthData\x1a;\n" +
	"\aLogPass\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"y\n" +
	"\aRefresh\x1a.\n" +
	"\aRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\x1a>\n" +
	"\bResponse\x122\n" +
	"\tauth_data\x18\x01 \x01(\v2\x15.zpotify_api.AuthDataR\bauthData\"\xe4\x01\n" +
	"\bAuthData\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12F\n" +
	"\x11access_expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0faccessExpiresAt\x12H\n" +
	"\x12refresh_expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x10refreshExpiresAt2\xc3\x03\n" +
	"\aAuthAPI\x12{\n" +
	"\x0eGetAuthMethods\x12#.zpotify_api.GetAuthMethods.Request\x1a$.zpotify_api.GetAuthMethods.Response\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/auth/auth_methods\x12X\n" +
	"\x04Auth\x12\x19.zpotify_api.Auth.Request\x1a\x1a.zpotify_api.Auth.Response\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/auth/sync\x12p\n" +
	"\tAuthAsync\x12!.zpotify_api.AuthViaAsync.Request\x1a\".zpotify_api.AuthViaAsync.Response\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/api/auth/async0\x01\x12o\n" +
	"\fRefreshToken\x12\x1c.zpotify_api.Refresh.Request\x1a\x1d.zpotify_api.Refresh.Response\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/auth/refresh_tokenB*\x92\x82\x19\f@zpotify/apiZ\x18/zpotify_api;zpotify_apib\x06proto3"

var (
	file_zpotify_auth_service_proto_rawDescOnce sync.Once
	file_zpotify_auth_service_proto_rawDescData []byte
)

func file_zpotify_auth_service_proto_rawDescGZIP() []byte {
	file_zpotify_auth_service_proto_rawDescOnce.Do(func() {
		file_zpotify_auth_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zpotify_auth_service_proto_rawDesc), len(file_zpotify_auth_service_proto_rawDesc)))
	})
	return file_zpotify_auth_service_proto_rawDescData
}

var file_zpotify_auth_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_zpotify_auth_service_proto_goTypes = []any{
	(*GetAuthMethods)(nil),          // 0: zpotify_api.GetAuthMethods
	(*AuthViaAsync)(nil),            // 1: zpotify_api.AuthViaAsync
	(*Auth)(nil),                    // 2: zpotify_api.Auth
	(*Refresh)(nil),                 // 3: zpotify_api.Refresh
	(*AuthData)(nil),                // 4: zpotify_api.AuthData
	(*GetAuthMethods_Request)(nil),  // 5: zpotify_api.GetAuthMethods.Request
	(*GetAuthMethods_Response)(nil), // 6: zpotify_api.GetAuthMethods.Response
	(*AuthViaAsync_Request)(nil),    // 7: zpotify_api.AuthViaAsync.Request
	(*AuthViaAsync_Response)(nil),   // 8: zpotify_api.AuthViaAsync.Response
	(*Auth_Request)(nil),            // 9: zpotify_api.Auth.Request
	(*Auth_Response)(nil),           // 10: zpotify_api.Auth.Response
	(*Auth_LogPass)(nil),            // 11: zpotify_api.Auth.LogPass
	(*Refresh_Request)(nil),         // 12: zpotify_api.Refresh.Request
	(*Refresh_Response)(nil),        // 13: zpotify_api.Refresh.Response
	(*timestamppb.Timestamp)(nil),   // 14: google.protobuf.Timestamp
	(AuthMethods)(0),                // 15: zpotify_api.AuthMethods
}
var file_zpotify_auth_service_proto_depIdxs = []int32{
	14, // 0: zpotify_api.AuthData.access_expires_at:type_name -> google.protobuf.Timestamp
	14, // 1: zpotify_api.AuthData.refresh_expires_at:type_name -> google.protobuf.Timestamp
	15, // 2: zpotify_api.GetAuthMethods.Response.auth_methods:type_name -> zpotify_api.AuthMethods
	4,  // 3: zpotify_api.AuthViaAsync.Response.auth_data:type_name -> zpotify_api.AuthData
	11, // 4: zpotify_api.Auth.Request.log_pass:type_name -> zpotify_api.Auth.LogPass
	4,  // 5: zpotify_api.Auth.Response.auth_data:type_name -> zpotify_api.AuthData
	4,  // 6: zpotify_api.Refresh.Response.auth_data:type_name -> zpotify_api.AuthData
	5,  // 7: zpotify_api.AuthAPI.GetAuthMethods:input_type -> zpotify_api.GetAuthMethods.Request
	9,  // 8: zpotify_api.AuthAPI.Auth:input_type -> zpotify_api.Auth.Request
	7,  // 9: zpotify_api.AuthAPI.AuthAsync:input_type -> zpotify_api.AuthViaAsync.Request
	12, // 10: zpotify_api.AuthAPI.RefreshToken:input_type -> zpotify_api.Refresh.Request
	6,  // 11: zpotify_api.AuthAPI.GetAuthMethods:output_type -> zpotify_api.GetAuthMethods.Response
	10, // 12: zpotify_api.AuthAPI.Auth:output_type -> zpotify_api.Auth.Response
	8,  // 13: zpotify_api.AuthAPI.AuthAsync:output_type -> zpotify_api.AuthViaAsync.Response
	13, // 14: zpotify_api.AuthAPI.RefreshToken:output_type -> zpotify_api.Refresh.Response
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_zpotify_auth_service_proto_init() }
func file_zpotify_auth_service_proto_init() {
	if File_zpotify_auth_service_proto != nil {
		return
	}
	file_zpotify_common_proto_init()
	file_zpotify_user_proto_init()
	file_zpotify_auth_service_proto_msgTypes[8].OneofWrappers = []any{
		(*AuthViaAsync_Response_AuthUuid)(nil),
		(*AuthViaAsync_Response_AuthData)(nil),
	}
	file_zpotify_auth_service_proto_msgTypes[9].OneofWrappers = []any{
		(*Auth_Request_LogPass)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zpotify_auth_service_proto_rawDesc), len(file_zpotify_auth_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zpotify_auth_service_proto_goTypes,
		DependencyIndexes: file_zpotify_auth_service_proto_depIdxs,
		MessageInfos:      file_zpotify_auth_service_proto_msgTypes,
	}.Build()
	File_zpotify_auth_service_proto = out.File
	file_zpotify_auth_service_proto_goTypes = nil
	file_zpotify_auth_service_proto_depIdxs = nil
}
