// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: zpotify_service_artists.proto

package zpotify_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArtistsAPI_ListArtist_FullMethodName = "/zpotify_api.ArtistsAPI/ListArtist"
)

// ArtistsAPIClient is the client API for ArtistsAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArtistsAPIClient interface {
	ListArtist(ctx context.Context, in *ListArtist_Request, opts ...grpc.CallOption) (*ListArtist_Response, error)
}

type artistsAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewArtistsAPIClient(cc grpc.ClientConnInterface) ArtistsAPIClient {
	return &artistsAPIClient{cc}
}

func (c *artistsAPIClient) ListArtist(ctx context.Context, in *ListArtist_Request, opts ...grpc.CallOption) (*ListArtist_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListArtist_Response)
	err := c.cc.Invoke(ctx, ArtistsAPI_ListArtist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArtistsAPIServer is the server API for ArtistsAPI service.
// All implementations must embed UnimplementedArtistsAPIServer
// for forward compatibility.
type ArtistsAPIServer interface {
	ListArtist(context.Context, *ListArtist_Request) (*ListArtist_Response, error)
	mustEmbedUnimplementedArtistsAPIServer()
}

// UnimplementedArtistsAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArtistsAPIServer struct{}

func (UnimplementedArtistsAPIServer) ListArtist(context.Context, *ListArtist_Request) (*ListArtist_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ListArtist not implemented")
}
func (UnimplementedArtistsAPIServer) mustEmbedUnimplementedArtistsAPIServer() {}
func (UnimplementedArtistsAPIServer) testEmbeddedByValue()                    {}

// UnsafeArtistsAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArtistsAPIServer will
// result in compilation errors.
type UnsafeArtistsAPIServer interface {
	mustEmbedUnimplementedArtistsAPIServer()
}

func RegisterArtistsAPIServer(s grpc.ServiceRegistrar, srv ArtistsAPIServer) {
	// If the following call panics, it indicates UnimplementedArtistsAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArtistsAPI_ServiceDesc, srv)
}

func _ArtistsAPI_ListArtist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListArtist_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtistsAPIServer).ListArtist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtistsAPI_ListArtist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtistsAPIServer).ListArtist(ctx, req.(*ListArtist_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// ArtistsAPI_ServiceDesc is the grpc.ServiceDesc for ArtistsAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArtistsAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zpotify_api.ArtistsAPI",
	HandlerType: (*ArtistsAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListArtist",
			Handler:    _ArtistsAPI_ListArtist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zpotify_service_artists.proto",
}
