// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: zpotify_service_song.proto

package zpotify_api

import (
	_ "go.redsock.ru/protoc-gen-npm/npmplugin"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSong) Reset() {
	*x = CreateSong{}
	mi := &file_zpotify_service_song_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSong) ProtoMessage() {}

func (x *CreateSong) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_song_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSong.ProtoReflect.Descriptor instead.
func (*CreateSong) Descriptor() ([]byte, []int) {
	return file_zpotify_service_song_proto_rawDescGZIP(), []int{0}
}

type UpdateSong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSong) Reset() {
	*x = UpdateSong{}
	mi := &file_zpotify_service_song_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSong) ProtoMessage() {}

func (x *UpdateSong) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_song_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSong.ProtoReflect.Descriptor instead.
func (*UpdateSong) Descriptor() ([]byte, []int) {
	return file_zpotify_service_song_proto_rawDescGZIP(), []int{1}
}

type CreateSong_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	ArtistUuids   []string               `protobuf:"bytes,2,rep,name=artist_uuids,json=artistUuids,proto3" json:"artist_uuids,omitempty"`
	FileId        int64                  `protobuf:"varint,3,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSong_Request) Reset() {
	*x = CreateSong_Request{}
	mi := &file_zpotify_service_song_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSong_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSong_Request) ProtoMessage() {}

func (x *CreateSong_Request) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_song_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSong_Request.ProtoReflect.Descriptor instead.
func (*CreateSong_Request) Descriptor() ([]byte, []int) {
	return file_zpotify_service_song_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CreateSong_Request) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateSong_Request) GetArtistUuids() []string {
	if x != nil {
		return x.ArtistUuids
	}
	return nil
}

func (x *CreateSong_Request) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

type CreateSong_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSong_Response) Reset() {
	*x = CreateSong_Response{}
	mi := &file_zpotify_service_song_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSong_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSong_Response) ProtoMessage() {}

func (x *CreateSong_Response) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_song_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSong_Response.ProtoReflect.Descriptor instead.
func (*CreateSong_Response) Descriptor() ([]byte, []int) {
	return file_zpotify_service_song_proto_rawDescGZIP(), []int{0, 1}
}

func (x *CreateSong_Response) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateSong_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ArtistUuids   []string               `protobuf:"bytes,3,rep,name=artist_uuids,json=artistUuids,proto3" json:"artist_uuids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSong_Request) Reset() {
	*x = UpdateSong_Request{}
	mi := &file_zpotify_service_song_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSong_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSong_Request) ProtoMessage() {}

func (x *UpdateSong_Request) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_song_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSong_Request.ProtoReflect.Descriptor instead.
func (*UpdateSong_Request) Descriptor() ([]byte, []int) {
	return file_zpotify_service_song_proto_rawDescGZIP(), []int{1, 0}
}

func (x *UpdateSong_Request) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateSong_Request) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateSong_Request) GetArtistUuids() []string {
	if x != nil {
		return x.ArtistUuids
	}
	return nil
}

type UpdateSong_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSong_Response) Reset() {
	*x = UpdateSong_Response{}
	mi := &file_zpotify_service_song_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSong_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSong_Response) ProtoMessage() {}

func (x *UpdateSong_Response) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_song_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSong_Response.ProtoReflect.Descriptor instead.
func (*UpdateSong_Response) Descriptor() ([]byte, []int) {
	return file_zpotify_service_song_proto_rawDescGZIP(), []int{1, 1}
}

var File_zpotify_service_song_proto protoreflect.FileDescriptor

const file_zpotify_service_song_proto_rawDesc = "" +
	"\n" +
	"\x1azpotify_service_song.proto\x12\vzpotify_api\x1a\x1cgoogle/api/annotations.proto\x1a\tnpm.proto\"\x85\x01\n" +
	"\n" +
	"CreateSong\x1a[\n" +
	"\aRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12!\n" +
	"\fartist_uuids\x18\x02 \x03(\tR\vartistUuids\x12\x17\n" +
	"\afile_id\x18\x03 \x01(\x03R\x06fileId\x1a\x1a\n" +
	"\bResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"l\n" +
	"\n" +
	"UpdateSong\x1aR\n" +
	"\aRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12!\n" +
	"\fartist_uuids\x18\x03 \x03(\tR\vartistUuids\x1a\n" +
	"\n" +
	"\bResponse2\xe5\x01\n" +
	"\aSongAPI\x12l\n" +
	"\n" +
	"CreateSong\x12\x1f.zpotify_api.CreateSong.Request\x1a .zpotify_api.CreateSong.Response\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/song/create\x12l\n" +
	"\n" +
	"UpdateSong\x12\x1f.zpotify_api.UpdateSong.Request\x1a .zpotify_api.UpdateSong.Response\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/song/updateB*\x92\x82\x19\f@zpotify/apiZ\x18/zpotify_api;zpotify_apib\x06proto3"

var (
	file_zpotify_service_song_proto_rawDescOnce sync.Once
	file_zpotify_service_song_proto_rawDescData []byte
)

func file_zpotify_service_song_proto_rawDescGZIP() []byte {
	file_zpotify_service_song_proto_rawDescOnce.Do(func() {
		file_zpotify_service_song_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zpotify_service_song_proto_rawDesc), len(file_zpotify_service_song_proto_rawDesc)))
	})
	return file_zpotify_service_song_proto_rawDescData
}

var file_zpotify_service_song_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_zpotify_service_song_proto_goTypes = []any{
	(*CreateSong)(nil),          // 0: zpotify_api.CreateSong
	(*UpdateSong)(nil),          // 1: zpotify_api.UpdateSong
	(*CreateSong_Request)(nil),  // 2: zpotify_api.CreateSong.Request
	(*CreateSong_Response)(nil), // 3: zpotify_api.CreateSong.Response
	(*UpdateSong_Request)(nil),  // 4: zpotify_api.UpdateSong.Request
	(*UpdateSong_Response)(nil), // 5: zpotify_api.UpdateSong.Response
}
var file_zpotify_service_song_proto_depIdxs = []int32{
	2, // 0: zpotify_api.SongAPI.CreateSong:input_type -> zpotify_api.CreateSong.Request
	4, // 1: zpotify_api.SongAPI.UpdateSong:input_type -> zpotify_api.UpdateSong.Request
	3, // 2: zpotify_api.SongAPI.CreateSong:output_type -> zpotify_api.CreateSong.Response
	5, // 3: zpotify_api.SongAPI.UpdateSong:output_type -> zpotify_api.UpdateSong.Response
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_zpotify_service_song_proto_init() }
func file_zpotify_service_song_proto_init() {
	if File_zpotify_service_song_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zpotify_service_song_proto_rawDesc), len(file_zpotify_service_song_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zpotify_service_song_proto_goTypes,
		DependencyIndexes: file_zpotify_service_song_proto_depIdxs,
		MessageInfos:      file_zpotify_service_song_proto_msgTypes,
	}.Build()
	File_zpotify_service_song_proto = out.File
	file_zpotify_service_song_proto_goTypes = nil
	file_zpotify_service_song_proto_depIdxs = nil
}
