// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: zpotify_service_playlist.proto

package zpotify_api

import (
	_ "go.redsock.ru/protoc-gen-npm/npmplugin"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListSongs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSongs) Reset() {
	*x = ListSongs{}
	mi := &file_zpotify_service_playlist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSongs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSongs) ProtoMessage() {}

func (x *ListSongs) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_playlist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSongs.ProtoReflect.Descriptor instead.
func (*ListSongs) Descriptor() ([]byte, []int) {
	return file_zpotify_service_playlist_proto_rawDescGZIP(), []int{0}
}

type DeleteSong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSong) Reset() {
	*x = DeleteSong{}
	mi := &file_zpotify_service_playlist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSong) ProtoMessage() {}

func (x *DeleteSong) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_playlist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSong.ProtoReflect.Descriptor instead.
func (*DeleteSong) Descriptor() ([]byte, []int) {
	return file_zpotify_service_playlist_proto_rawDescGZIP(), []int{1}
}

type CreatePlaylist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlaylist) Reset() {
	*x = CreatePlaylist{}
	mi := &file_zpotify_service_playlist_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlaylist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlaylist) ProtoMessage() {}

func (x *CreatePlaylist) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_playlist_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlaylist.ProtoReflect.Descriptor instead.
func (*CreatePlaylist) Descriptor() ([]byte, []int) {
	return file_zpotify_service_playlist_proto_rawDescGZIP(), []int{2}
}

type UpdatePlaylist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlaylist) Reset() {
	*x = UpdatePlaylist{}
	mi := &file_zpotify_service_playlist_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlaylist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlaylist) ProtoMessage() {}

func (x *UpdatePlaylist) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_playlist_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlaylist.ProtoReflect.Descriptor instead.
func (*UpdatePlaylist) Descriptor() ([]byte, []int) {
	return file_zpotify_service_playlist_proto_rawDescGZIP(), []int{3}
}

type GetPlaylist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlaylist) Reset() {
	*x = GetPlaylist{}
	mi := &file_zpotify_service_playlist_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlaylist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlaylist) ProtoMessage() {}

func (x *GetPlaylist) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_playlist_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlaylist.ProtoReflect.Descriptor instead.
func (*GetPlaylist) Descriptor() ([]byte, []int) {
	return file_zpotify_service_playlist_proto_rawDescGZIP(), []int{4}
}

type ChangeSongsOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeSongsOrder) Reset() {
	*x = ChangeSongsOrder{}
	mi := &file_zpotify_service_playlist_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeSongsOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeSongsOrder) ProtoMessage() {}

func (x *ChangeSongsOrder) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_playlist_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeSongsOrder.ProtoReflect.Descriptor instead.
func (*ChangeSongsOrder) Descriptor() ([]byte, []int) {
	return file_zpotify_service_playlist_proto_rawDescGZIP(), []int{5}
}

type AddSongToPlaylist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSongToPlaylist) Reset() {
	*x = AddSongToPlaylist{}
	mi := &file_zpotify_service_playlist_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSongToPlaylist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSongToPlaylist) ProtoMessage() {}

func (x *AddSongToPlaylist) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_playlist_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSongToPlaylist.ProtoReflect.Descriptor instead.
func (*AddSongToPlaylist) Descriptor() ([]byte, []int) {
	return file_zpotify_service_playlist_proto_rawDescGZIP(), []int{6}
}

type ListPlaylists struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlaylists) Reset() {
	*x = ListPlaylists{}
	mi := &file_zpotify_service_playlist_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlaylists) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlaylists) ProtoMessage() {}

func (x *ListPlaylists) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_playlist_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlaylists.ProtoReflect.Descriptor instead.
func (*ListPlaylists) Descriptor() ([]byte, []int) {
	return file_zpotify_service_playlist_proto_rawDescGZIP(), []int{7}
}

type ListSongs_Request struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Paging     *Paging                `protobuf:"bytes,1,opt,name=paging,proto3" json:"paging,omitempty"`
	RandomHash *uint64                `protobuf:"varint,2,opt,name=random_hash,json=randomHash,proto3,oneof" json:"random_hash,omitempty"`
	// by default returns songs from global queue (last added tracks)
	PlaylistUuid  *string `protobuf:"bytes,3,opt,name=playlist_uuid,json=playlistUuid,proto3,oneof" json:"playlist_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSongs_Request) Reset() {
	*x = ListSongs_Request{}
	mi := &file_zpotify_service_playlist_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSongs_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSongs_Request) ProtoMessage() {}

func (x *ListSongs_Request) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_playlist_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSongs_Request.ProtoReflect.Descriptor instead.
func (*ListSongs_Request) Descriptor() ([]byte, []int) {
	return file_zpotify_service_playlist_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ListSongs_Request) GetPaging() *Paging {
	if x != nil {
		return x.Paging
	}
	return nil
}

func (x *ListSongs_Request) GetRandomHash() uint64 {
	if x != nil && x.RandomHash != nil {
		return *x.RandomHash
	}
	return 0
}

func (x *ListSongs_Request) GetPlaylistUuid() string {
	if x != nil && x.PlaylistUuid != nil {
		return *x.PlaylistUuid
	}
	return ""
}

type ListSongs_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Songs         []*SongBase            `protobuf:"bytes,1,rep,name=songs,proto3" json:"songs,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSongs_Response) Reset() {
	*x = ListSongs_Response{}
	mi := &file_zpotify_service_playlist_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSongs_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSongs_Response) ProtoMessage() {}

func (x *ListSongs_Response) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_playlist_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSongs_Response.ProtoReflect.Descriptor instead.
func (*ListSongs_Response) Descriptor() ([]byte, []int) {
	return file_zpotify_service_playlist_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ListSongs_Response) GetSongs() []*SongBase {
	if x != nil {
		return x.Songs
	}
	return nil
}

func (x *ListSongs_Response) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DeleteSong_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlaylistUuid  string                 `protobuf:"bytes,1,opt,name=playlist_uuid,json=playlistUuid,proto3" json:"playlist_uuid,omitempty"`
	SongId        int32                  `protobuf:"varint,2,opt,name=song_id,json=songId,proto3" json:"song_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSong_Request) Reset() {
	*x = DeleteSong_Request{}
	mi := &file_zpotify_service_playlist_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSong_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSong_Request) ProtoMessage() {}

func (x *DeleteSong_Request) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_playlist_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSong_Request.ProtoReflect.Descriptor instead.
func (*DeleteSong_Request) Descriptor() ([]byte, []int) {
	return file_zpotify_service_playlist_proto_rawDescGZIP(), []int{1, 0}
}

func (x *DeleteSong_Request) GetPlaylistUuid() string {
	if x != nil {
		return x.PlaylistUuid
	}
	return ""
}

func (x *DeleteSong_Request) GetSongId() int32 {
	if x != nil {
		return x.SongId
	}
	return 0
}

type DeleteSong_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSong_Response) Reset() {
	*x = DeleteSong_Response{}
	mi := &file_zpotify_service_playlist_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSong_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSong_Response) ProtoMessage() {}

func (x *DeleteSong_Response) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_playlist_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSong_Response.ProtoReflect.Descriptor instead.
func (*DeleteSong_Response) Descriptor() ([]byte, []int) {
	return file_zpotify_service_playlist_proto_rawDescGZIP(), []int{1, 1}
}

type CreatePlaylist_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	IsPublic      bool                   `protobuf:"varint,3,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	ArtistUuids   []string               `protobuf:"bytes,4,rep,name=artist_uuids,json=artistUuids,proto3" json:"artist_uuids,omitempty"`
	CoverFileId   *int64                 `protobuf:"varint,5,opt,name=cover_file_id,json=coverFileId,proto3,oneof" json:"cover_file_id,omitempty"`
	Year          *int32                 `protobuf:"varint,6,opt,name=year,proto3,oneof" json:"year,omitempty"`
	Chips         []*PlaylistChip        `protobuf:"bytes,7,rep,name=chips,proto3" json:"chips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlaylist_Request) Reset() {
	*x = CreatePlaylist_Request{}
	mi := &file_zpotify_service_playlist_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlaylist_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlaylist_Request) ProtoMessage() {}

func (x *CreatePlaylist_Request) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_playlist_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlaylist_Request.ProtoReflect.Descriptor instead.
func (*CreatePlaylist_Request) Descriptor() ([]byte, []int) {
	return file_zpotify_service_playlist_proto_rawDescGZIP(), []int{2, 0}
}

func (x *CreatePlaylist_Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePlaylist_Request) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreatePlaylist_Request) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *CreatePlaylist_Request) GetArtistUuids() []string {
	if x != nil {
		return x.ArtistUuids
	}
	return nil
}

func (x *CreatePlaylist_Request) GetCoverFileId() int64 {
	if x != nil && x.CoverFileId != nil {
		return *x.CoverFileId
	}
	return 0
}

func (x *CreatePlaylist_Request) GetYear() int32 {
	if x != nil && x.Year != nil {
		return *x.Year
	}
	return 0
}

func (x *CreatePlaylist_Request) GetChips() []*PlaylistChip {
	if x != nil {
		return x.Chips
	}
	return nil
}

type CreatePlaylist_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlaylist_Response) Reset() {
	*x = CreatePlaylist_Response{}
	mi := &file_zpotify_service_playlist_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlaylist_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlaylist_Response) ProtoMessage() {}

func (x *CreatePlaylist_Response) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_playlist_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlaylist_Response.ProtoReflect.Descriptor instead.
func (*CreatePlaylist_Response) Descriptor() ([]byte, []int) {
	return file_zpotify_service_playlist_proto_rawDescGZIP(), []int{2, 1}
}

func (x *CreatePlaylist_Response) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type UpdatePlaylist_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	IsPublic      *bool                  `protobuf:"varint,4,opt,name=is_public,json=isPublic,proto3,oneof" json:"is_public,omitempty"`
	ArtistUuids   []string               `protobuf:"bytes,5,rep,name=artist_uuids,json=artistUuids,proto3" json:"artist_uuids,omitempty"`
	CoverFileId   *int64                 `protobuf:"varint,6,opt,name=cover_file_id,json=coverFileId,proto3,oneof" json:"cover_file_id,omitempty"`
	Year          *int32                 `protobuf:"varint,7,opt,name=year,proto3,oneof" json:"year,omitempty"`
	Chips         []*PlaylistChip        `protobuf:"bytes,8,rep,name=chips,proto3" json:"chips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlaylist_Request) Reset() {
	*x = UpdatePlaylist_Request{}
	mi := &file_zpotify_service_playlist_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlaylist_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlaylist_Request) ProtoMessage() {}

func (x *UpdatePlaylist_Request) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_playlist_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlaylist_Request.ProtoReflect.Descriptor instead.
func (*UpdatePlaylist_Request) Descriptor() ([]byte, []int) {
	return file_zpotify_service_playlist_proto_rawDescGZIP(), []int{3, 0}
}

func (x *UpdatePlaylist_Request) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UpdatePlaylist_Request) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdatePlaylist_Request) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdatePlaylist_Request) GetIsPublic() bool {
	if x != nil && x.IsPublic != nil {
		return *x.IsPublic
	}
	return false
}

func (x *UpdatePlaylist_Request) GetArtistUuids() []string {
	if x != nil {
		return x.ArtistUuids
	}
	return nil
}

func (x *UpdatePlaylist_Request) GetCoverFileId() int64 {
	if x != nil && x.CoverFileId != nil {
		return *x.CoverFileId
	}
	return 0
}

func (x *UpdatePlaylist_Request) GetYear() int32 {
	if x != nil && x.Year != nil {
		return *x.Year
	}
	return 0
}

func (x *UpdatePlaylist_Request) GetChips() []*PlaylistChip {
	if x != nil {
		return x.Chips
	}
	return nil
}

type UpdatePlaylist_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlaylist_Response) Reset() {
	*x = UpdatePlaylist_Response{}
	mi := &file_zpotify_service_playlist_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlaylist_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlaylist_Response) ProtoMessage() {}

func (x *UpdatePlaylist_Response) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_playlist_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlaylist_Response.ProtoReflect.Descriptor instead.
func (*UpdatePlaylist_Response) Descriptor() ([]byte, []int) {
	return file_zpotify_service_playlist_proto_rawDescGZIP(), []int{3, 1}
}

type GetPlaylist_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlaylist_Request) Reset() {
	*x = GetPlaylist_Request{}
	mi := &file_zpotify_service_playlist_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlaylist_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlaylist_Request) ProtoMessage() {}

func (x *GetPlaylist_Request) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_playlist_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlaylist_Request.ProtoReflect.Descriptor instead.
func (*GetPlaylist_Request) Descriptor() ([]byte, []int) {
	return file_zpotify_service_playlist_proto_rawDescGZIP(), []int{4, 0}
}

func (x *GetPlaylist_Request) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetPlaylist_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Playlist      *Playlist              `protobuf:"bytes,1,opt,name=playlist,proto3" json:"playlist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlaylist_Response) Reset() {
	*x = GetPlaylist_Response{}
	mi := &file_zpotify_service_playlist_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlaylist_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlaylist_Response) ProtoMessage() {}

func (x *GetPlaylist_Response) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_playlist_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlaylist_Response.ProtoReflect.Descriptor instead.
func (*GetPlaylist_Response) Descriptor() ([]byte, []int) {
	return file_zpotify_service_playlist_proto_rawDescGZIP(), []int{4, 1}
}

func (x *GetPlaylist_Response) GetPlaylist() *Playlist {
	if x != nil {
		return x.Playlist
	}
	return nil
}

type ChangeSongsOrder_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlaylistUuid  string                 `protobuf:"bytes,1,opt,name=playlist_uuid,json=playlistUuid,proto3" json:"playlist_uuid,omitempty"`
	SongIds       []int64                `protobuf:"varint,2,rep,packed,name=song_ids,json=songIds,proto3" json:"song_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeSongsOrder_Request) Reset() {
	*x = ChangeSongsOrder_Request{}
	mi := &file_zpotify_service_playlist_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeSongsOrder_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeSongsOrder_Request) ProtoMessage() {}

func (x *ChangeSongsOrder_Request) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_playlist_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeSongsOrder_Request.ProtoReflect.Descriptor instead.
func (*ChangeSongsOrder_Request) Descriptor() ([]byte, []int) {
	return file_zpotify_service_playlist_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ChangeSongsOrder_Request) GetPlaylistUuid() string {
	if x != nil {
		return x.PlaylistUuid
	}
	return ""
}

func (x *ChangeSongsOrder_Request) GetSongIds() []int64 {
	if x != nil {
		return x.SongIds
	}
	return nil
}

type ChangeSongsOrder_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeSongsOrder_Response) Reset() {
	*x = ChangeSongsOrder_Response{}
	mi := &file_zpotify_service_playlist_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeSongsOrder_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeSongsOrder_Response) ProtoMessage() {}

func (x *ChangeSongsOrder_Response) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_playlist_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeSongsOrder_Response.ProtoReflect.Descriptor instead.
func (*ChangeSongsOrder_Response) Descriptor() ([]byte, []int) {
	return file_zpotify_service_playlist_proto_rawDescGZIP(), []int{5, 1}
}

type AddSongToPlaylist_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlaylistUuid  string                 `protobuf:"bytes,1,opt,name=playlist_uuid,json=playlistUuid,proto3" json:"playlist_uuid,omitempty"`
	SongId        int32                  `protobuf:"varint,2,opt,name=song_id,json=songId,proto3" json:"song_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSongToPlaylist_Request) Reset() {
	*x = AddSongToPlaylist_Request{}
	mi := &file_zpotify_service_playlist_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSongToPlaylist_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSongToPlaylist_Request) ProtoMessage() {}

func (x *AddSongToPlaylist_Request) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_playlist_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSongToPlaylist_Request.ProtoReflect.Descriptor instead.
func (*AddSongToPlaylist_Request) Descriptor() ([]byte, []int) {
	return file_zpotify_service_playlist_proto_rawDescGZIP(), []int{6, 0}
}

func (x *AddSongToPlaylist_Request) GetPlaylistUuid() string {
	if x != nil {
		return x.PlaylistUuid
	}
	return ""
}

func (x *AddSongToPlaylist_Request) GetSongId() int32 {
	if x != nil {
		return x.SongId
	}
	return 0
}

type AddSongToPlaylist_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSongToPlaylist_Response) Reset() {
	*x = AddSongToPlaylist_Response{}
	mi := &file_zpotify_service_playlist_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSongToPlaylist_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSongToPlaylist_Response) ProtoMessage() {}

func (x *AddSongToPlaylist_Response) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_playlist_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSongToPlaylist_Response.ProtoReflect.Descriptor instead.
func (*AddSongToPlaylist_Response) Descriptor() ([]byte, []int) {
	return file_zpotify_service_playlist_proto_rawDescGZIP(), []int{6, 1}
}

type ListPlaylists_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paging        *Paging                `protobuf:"bytes,1,opt,name=paging,proto3" json:"paging,omitempty"`
	ByAuthedUser  *bool                  `protobuf:"varint,2,opt,name=by_authed_user,json=byAuthedUser,proto3,oneof" json:"by_authed_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlaylists_Request) Reset() {
	*x = ListPlaylists_Request{}
	mi := &file_zpotify_service_playlist_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlaylists_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlaylists_Request) ProtoMessage() {}

func (x *ListPlaylists_Request) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_playlist_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlaylists_Request.ProtoReflect.Descriptor instead.
func (*ListPlaylists_Request) Descriptor() ([]byte, []int) {
	return file_zpotify_service_playlist_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ListPlaylists_Request) GetPaging() *Paging {
	if x != nil {
		return x.Paging
	}
	return nil
}

func (x *ListPlaylists_Request) GetByAuthedUser() bool {
	if x != nil && x.ByAuthedUser != nil {
		return *x.ByAuthedUser
	}
	return false
}

type ListPlaylists_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Playlists     []*Playlist            `protobuf:"bytes,1,rep,name=playlists,proto3" json:"playlists,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlaylists_Response) Reset() {
	*x = ListPlaylists_Response{}
	mi := &file_zpotify_service_playlist_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlaylists_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlaylists_Response) ProtoMessage() {}

func (x *ListPlaylists_Response) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_service_playlist_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlaylists_Response.ProtoReflect.Descriptor instead.
func (*ListPlaylists_Response) Descriptor() ([]byte, []int) {
	return file_zpotify_service_playlist_proto_rawDescGZIP(), []int{7, 1}
}

func (x *ListPlaylists_Response) GetPlaylists() []*Playlist {
	if x != nil {
		return x.Playlists
	}
	return nil
}

func (x *ListPlaylists_Response) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_zpotify_service_playlist_proto protoreflect.FileDescriptor

const file_zpotify_service_playlist_proto_rawDesc = "" +
	"\n" +
	"\x1ezpotify_service_playlist.proto\x12\vzpotify_api\x1a\x1cgoogle/api/annotations.proto\x1a\tnpm.proto\x1a\x14zpotify_common.proto\"\x85\x02\n" +
	"\tListSongs\x1a\xa8\x01\n" +
	"\aRequest\x12+\n" +
	"\x06paging\x18\x01 \x01(\v2\x13.zpotify_api.PagingR\x06paging\x12$\n" +
	"\vrandom_hash\x18\x02 \x01(\x04H\x00R\n" +
	"randomHash\x88\x01\x01\x12(\n" +
	"\rplaylist_uuid\x18\x03 \x01(\tH\x01R\fplaylistUuid\x88\x01\x01B\x0e\n" +
	"\f_random_hashB\x10\n" +
	"\x0e_playlist_uuid\x1aM\n" +
	"\bResponse\x12+\n" +
	"\x05songs\x18\x01 \x03(\v2\x15.zpotify_api.SongBaseR\x05songs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\"a\n" +
	"\n" +
	"DeleteSong\x1aG\n" +
	"\aRequest\x12#\n" +
	"\rplaylist_uuid\x18\x01 \x01(\tR\fplaylistUuid\x12\x17\n" +
	"\asong_id\x18\x02 \x01(\x05R\x06songId\x1a\n" +
	"\n" +
	"\bResponse\"\xd5\x02\n" +
	"\x0eCreatePlaylist\x1a\xa2\x02\n" +
	"\aRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1b\n" +
	"\tis_public\x18\x03 \x01(\bR\bisPublic\x12!\n" +
	"\fartist_uuids\x18\x04 \x03(\tR\vartistUuids\x12'\n" +
	"\rcover_file_id\x18\x05 \x01(\x03H\x01R\vcoverFileId\x88\x01\x01\x12\x17\n" +
	"\x04year\x18\x06 \x01(\x05H\x02R\x04year\x88\x01\x01\x12/\n" +
	"\x05chips\x18\a \x03(\v2\x19.zpotify_api.PlaylistChipR\x05chipsB\x0e\n" +
	"\f_descriptionB\x10\n" +
	"\x0e_cover_file_idB\a\n" +
	"\x05_year\x1a\x1e\n" +
	"\bResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\xf6\x02\n" +
	"\x0eUpdatePlaylist\x1a\xd7\x02\n" +
	"\aRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12 \n" +
	"\tis_public\x18\x04 \x01(\bH\x02R\bisPublic\x88\x01\x01\x12!\n" +
	"\fartist_uuids\x18\x05 \x03(\tR\vartistUuids\x12'\n" +
	"\rcover_file_id\x18\x06 \x01(\x03H\x03R\vcoverFileId\x88\x01\x01\x12\x17\n" +
	"\x04year\x18\a \x01(\x05H\x04R\x04year\x88\x01\x01\x12/\n" +
	"\x05chips\x18\b \x03(\v2\x19.zpotify_api.PlaylistChipR\x05chipsB\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\f\n" +
	"\n" +
	"_is_publicB\x10\n" +
	"\x0e_cover_file_idB\a\n" +
	"\x05_year\x1a\n" +
	"\n" +
	"\bResponse\"k\n" +
	"\vGetPlaylist\x1a\x1d\n" +
	"\aRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x1a=\n" +
	"\bResponse\x121\n" +
	"\bplaylist\x18\x01 \x01(\v2\x15.zpotify_api.PlaylistR\bplaylist\"i\n" +
	"\x10ChangeSongsOrder\x1aI\n" +
	"\aRequest\x12#\n" +
	"\rplaylist_uuid\x18\x01 \x01(\tR\fplaylistUuid\x12\x19\n" +
	"\bsong_ids\x18\x02 \x03(\x03R\asongIds\x1a\n" +
	"\n" +
	"\bResponse\"h\n" +
	"\x11AddSongToPlaylist\x1aG\n" +
	"\aRequest\x12#\n" +
	"\rplaylist_uuid\x18\x01 \x01(\tR\fplaylistUuid\x12\x17\n" +
	"\asong_id\x18\x02 \x01(\x05R\x06songId\x1a\n" +
	"\n" +
	"\bResponse\"\xdc\x01\n" +
	"\rListPlaylists\x1at\n" +
	"\aRequest\x12+\n" +
	"\x06paging\x18\x01 \x01(\v2\x13.zpotify_api.PagingR\x06paging\x12)\n" +
	"\x0eby_authed_user\x18\x02 \x01(\bH\x00R\fbyAuthedUser\x88\x01\x01B\x11\n" +
	"\x0f_by_authed_user\x1aU\n" +
	"\bResponse\x123\n" +
	"\tplaylists\x18\x01 \x03(\v2\x15.zpotify_api.PlaylistR\tplaylists\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total2\xed\a\n" +
	"\vPlaylistAPI\x12|\n" +
	"\x0eCreatePlaylist\x12#.zpotify_api.CreatePlaylist.Request\x1a$.zpotify_api.CreatePlaylist.Response\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/playlist/create\x12p\n" +
	"\vGetPlaylist\x12 .zpotify_api.GetPlaylist.Request\x1a!.zpotify_api.GetPlaylist.Response\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/playlist/{uuid}\x12u\n" +
	"\n" +
	"DeleteSong\x12\x1f.zpotify_api.DeleteSong.Request\x1a .zpotify_api.DeleteSong.Response\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/playlist/delete_song\x12l\n" +
	"\tListSongs\x12\x1e.zpotify_api.ListSongs.Request\x1a\x1f.zpotify_api.ListSongs.Response\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/playlist/songs\x12\x87\x01\n" +
	"\x10ChangeSongsOrder\x12%.zpotify_api.ChangeSongsOrder.Request\x1a&.zpotify_api.ChangeSongsOrder.Response\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/playlist/songs/order\x12\x87\x01\n" +
	"\x11AddSongToPlaylist\x12&.zpotify_api.AddSongToPlaylist.Request\x1a'.zpotify_api.AddSongToPlaylist.Response\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/playlist/add_song\x12|\n" +
	"\x0eUpdatePlaylist\x12#.zpotify_api.UpdatePlaylist.Request\x1a$.zpotify_api.UpdatePlaylist.Response\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/playlist/update\x12w\n" +
	"\rListPlaylists\x12\".zpotify_api.ListPlaylists.Request\x1a#.zpotify_api.ListPlaylists.Response\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/playlist/listB*\x92\x82\x19\f@zpotify/apiZ\x18/zpotify_api;zpotify_apib\x06proto3"

var (
	file_zpotify_service_playlist_proto_rawDescOnce sync.Once
	file_zpotify_service_playlist_proto_rawDescData []byte
)

func file_zpotify_service_playlist_proto_rawDescGZIP() []byte {
	file_zpotify_service_playlist_proto_rawDescOnce.Do(func() {
		file_zpotify_service_playlist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zpotify_service_playlist_proto_rawDesc), len(file_zpotify_service_playlist_proto_rawDesc)))
	})
	return file_zpotify_service_playlist_proto_rawDescData
}

var file_zpotify_service_playlist_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_zpotify_service_playlist_proto_goTypes = []any{
	(*ListSongs)(nil),                  // 0: zpotify_api.ListSongs
	(*DeleteSong)(nil),                 // 1: zpotify_api.DeleteSong
	(*CreatePlaylist)(nil),             // 2: zpotify_api.CreatePlaylist
	(*UpdatePlaylist)(nil),             // 3: zpotify_api.UpdatePlaylist
	(*GetPlaylist)(nil),                // 4: zpotify_api.GetPlaylist
	(*ChangeSongsOrder)(nil),           // 5: zpotify_api.ChangeSongsOrder
	(*AddSongToPlaylist)(nil),          // 6: zpotify_api.AddSongToPlaylist
	(*ListPlaylists)(nil),              // 7: zpotify_api.ListPlaylists
	(*ListSongs_Request)(nil),          // 8: zpotify_api.ListSongs.Request
	(*ListSongs_Response)(nil),         // 9: zpotify_api.ListSongs.Response
	(*DeleteSong_Request)(nil),         // 10: zpotify_api.DeleteSong.Request
	(*DeleteSong_Response)(nil),        // 11: zpotify_api.DeleteSong.Response
	(*CreatePlaylist_Request)(nil),     // 12: zpotify_api.CreatePlaylist.Request
	(*CreatePlaylist_Response)(nil),    // 13: zpotify_api.CreatePlaylist.Response
	(*UpdatePlaylist_Request)(nil),     // 14: zpotify_api.UpdatePlaylist.Request
	(*UpdatePlaylist_Response)(nil),    // 15: zpotify_api.UpdatePlaylist.Response
	(*GetPlaylist_Request)(nil),        // 16: zpotify_api.GetPlaylist.Request
	(*GetPlaylist_Response)(nil),       // 17: zpotify_api.GetPlaylist.Response
	(*ChangeSongsOrder_Request)(nil),   // 18: zpotify_api.ChangeSongsOrder.Request
	(*ChangeSongsOrder_Response)(nil),  // 19: zpotify_api.ChangeSongsOrder.Response
	(*AddSongToPlaylist_Request)(nil),  // 20: zpotify_api.AddSongToPlaylist.Request
	(*AddSongToPlaylist_Response)(nil), // 21: zpotify_api.AddSongToPlaylist.Response
	(*ListPlaylists_Request)(nil),      // 22: zpotify_api.ListPlaylists.Request
	(*ListPlaylists_Response)(nil),     // 23: zpotify_api.ListPlaylists.Response
	(*Paging)(nil),                     // 24: zpotify_api.Paging
	(*SongBase)(nil),                   // 25: zpotify_api.SongBase
	(*PlaylistChip)(nil),               // 26: zpotify_api.PlaylistChip
	(*Playlist)(nil),                   // 27: zpotify_api.Playlist
}
var file_zpotify_service_playlist_proto_depIdxs = []int32{
	24, // 0: zpotify_api.ListSongs.Request.paging:type_name -> zpotify_api.Paging
	25, // 1: zpotify_api.ListSongs.Response.songs:type_name -> zpotify_api.SongBase
	26, // 2: zpotify_api.CreatePlaylist.Request.chips:type_name -> zpotify_api.PlaylistChip
	26, // 3: zpotify_api.UpdatePlaylist.Request.chips:type_name -> zpotify_api.PlaylistChip
	27, // 4: zpotify_api.GetPlaylist.Response.playlist:type_name -> zpotify_api.Playlist
	24, // 5: zpotify_api.ListPlaylists.Request.paging:type_name -> zpotify_api.Paging
	27, // 6: zpotify_api.ListPlaylists.Response.playlists:type_name -> zpotify_api.Playlist
	12, // 7: zpotify_api.PlaylistAPI.CreatePlaylist:input_type -> zpotify_api.CreatePlaylist.Request
	16, // 8: zpotify_api.PlaylistAPI.GetPlaylist:input_type -> zpotify_api.GetPlaylist.Request
	10, // 9: zpotify_api.PlaylistAPI.DeleteSong:input_type -> zpotify_api.DeleteSong.Request
	8,  // 10: zpotify_api.PlaylistAPI.ListSongs:input_type -> zpotify_api.ListSongs.Request
	18, // 11: zpotify_api.PlaylistAPI.ChangeSongsOrder:input_type -> zpotify_api.ChangeSongsOrder.Request
	20, // 12: zpotify_api.PlaylistAPI.AddSongToPlaylist:input_type -> zpotify_api.AddSongToPlaylist.Request
	14, // 13: zpotify_api.PlaylistAPI.UpdatePlaylist:input_type -> zpotify_api.UpdatePlaylist.Request
	22, // 14: zpotify_api.PlaylistAPI.ListPlaylists:input_type -> zpotify_api.ListPlaylists.Request
	13, // 15: zpotify_api.PlaylistAPI.CreatePlaylist:output_type -> zpotify_api.CreatePlaylist.Response
	17, // 16: zpotify_api.PlaylistAPI.GetPlaylist:output_type -> zpotify_api.GetPlaylist.Response
	11, // 17: zpotify_api.PlaylistAPI.DeleteSong:output_type -> zpotify_api.DeleteSong.Response
	9,  // 18: zpotify_api.PlaylistAPI.ListSongs:output_type -> zpotify_api.ListSongs.Response
	19, // 19: zpotify_api.PlaylistAPI.ChangeSongsOrder:output_type -> zpotify_api.ChangeSongsOrder.Response
	21, // 20: zpotify_api.PlaylistAPI.AddSongToPlaylist:output_type -> zpotify_api.AddSongToPlaylist.Response
	15, // 21: zpotify_api.PlaylistAPI.UpdatePlaylist:output_type -> zpotify_api.UpdatePlaylist.Response
	23, // 22: zpotify_api.PlaylistAPI.ListPlaylists:output_type -> zpotify_api.ListPlaylists.Response
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_zpotify_service_playlist_proto_init() }
func file_zpotify_service_playlist_proto_init() {
	if File_zpotify_service_playlist_proto != nil {
		return
	}
	file_zpotify_common_proto_init()
	file_zpotify_service_playlist_proto_msgTypes[8].OneofWrappers = []any{}
	file_zpotify_service_playlist_proto_msgTypes[12].OneofWrappers = []any{}
	file_zpotify_service_playlist_proto_msgTypes[14].OneofWrappers = []any{}
	file_zpotify_service_playlist_proto_msgTypes[22].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zpotify_service_playlist_proto_rawDesc), len(file_zpotify_service_playlist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zpotify_service_playlist_proto_goTypes,
		DependencyIndexes: file_zpotify_service_playlist_proto_depIdxs,
		MessageInfos:      file_zpotify_service_playlist_proto_msgTypes,
	}.Build()
	File_zpotify_service_playlist_proto = out.File
	file_zpotify_service_playlist_proto_goTypes = nil
	file_zpotify_service_playlist_proto_depIdxs = nil
}
