// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: zpotify_service_notification.proto

package zpotify_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NotificationAPI_GetNotificationSummary_FullMethodName = "/zpotify_api.NotificationAPI/GetNotificationSummary"
	NotificationAPI_ListNotifications_FullMethodName      = "/zpotify_api.NotificationAPI/ListNotifications"
	NotificationAPI_MarkNotificationRead_FullMethodName   = "/zpotify_api.NotificationAPI/MarkNotificationRead"
	NotificationAPI_ConsentNotification_FullMethodName    = "/zpotify_api.NotificationAPI/ConsentNotification"
)

// NotificationAPIClient is the client API for NotificationAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationAPIClient interface {
	GetNotificationSummary(ctx context.Context, in *GetNotificationSummary_Request, opts ...grpc.CallOption) (*GetNotificationSummary_Response, error)
	ListNotifications(ctx context.Context, in *ListNotifications_Request, opts ...grpc.CallOption) (*ListNotifications_Response, error)
	MarkNotificationRead(ctx context.Context, in *MarkNotificationRead_Request, opts ...grpc.CallOption) (*MarkNotificationRead_Response, error)
	ConsentNotification(ctx context.Context, in *ConsentNotification_Request, opts ...grpc.CallOption) (*ConsentNotification_Response, error)
}

type notificationAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationAPIClient(cc grpc.ClientConnInterface) NotificationAPIClient {
	return &notificationAPIClient{cc}
}

func (c *notificationAPIClient) GetNotificationSummary(ctx context.Context, in *GetNotificationSummary_Request, opts ...grpc.CallOption) (*GetNotificationSummary_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNotificationSummary_Response)
	err := c.cc.Invoke(ctx, NotificationAPI_GetNotificationSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationAPIClient) ListNotifications(ctx context.Context, in *ListNotifications_Request, opts ...grpc.CallOption) (*ListNotifications_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNotifications_Response)
	err := c.cc.Invoke(ctx, NotificationAPI_ListNotifications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationAPIClient) MarkNotificationRead(ctx context.Context, in *MarkNotificationRead_Request, opts ...grpc.CallOption) (*MarkNotificationRead_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkNotificationRead_Response)
	err := c.cc.Invoke(ctx, NotificationAPI_MarkNotificationRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationAPIClient) ConsentNotification(ctx context.Context, in *ConsentNotification_Request, opts ...grpc.CallOption) (*ConsentNotification_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsentNotification_Response)
	err := c.cc.Invoke(ctx, NotificationAPI_ConsentNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationAPIServer is the server API for NotificationAPI service.
// All implementations must embed UnimplementedNotificationAPIServer
// for forward compatibility.
type NotificationAPIServer interface {
	GetNotificationSummary(context.Context, *GetNotificationSummary_Request) (*GetNotificationSummary_Response, error)
	ListNotifications(context.Context, *ListNotifications_Request) (*ListNotifications_Response, error)
	MarkNotificationRead(context.Context, *MarkNotificationRead_Request) (*MarkNotificationRead_Response, error)
	ConsentNotification(context.Context, *ConsentNotification_Request) (*ConsentNotification_Response, error)
	mustEmbedUnimplementedNotificationAPIServer()
}

// UnimplementedNotificationAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotificationAPIServer struct{}

func (UnimplementedNotificationAPIServer) GetNotificationSummary(context.Context, *GetNotificationSummary_Request) (*GetNotificationSummary_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNotificationSummary not implemented")
}
func (UnimplementedNotificationAPIServer) ListNotifications(context.Context, *ListNotifications_Request) (*ListNotifications_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNotifications not implemented")
}
func (UnimplementedNotificationAPIServer) MarkNotificationRead(context.Context, *MarkNotificationRead_Request) (*MarkNotificationRead_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkNotificationRead not implemented")
}
func (UnimplementedNotificationAPIServer) ConsentNotification(context.Context, *ConsentNotification_Request) (*ConsentNotification_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsentNotification not implemented")
}
func (UnimplementedNotificationAPIServer) mustEmbedUnimplementedNotificationAPIServer() {}
func (UnimplementedNotificationAPIServer) testEmbeddedByValue()                         {}

// UnsafeNotificationAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationAPIServer will
// result in compilation errors.
type UnsafeNotificationAPIServer interface {
	mustEmbedUnimplementedNotificationAPIServer()
}

func RegisterNotificationAPIServer(s grpc.ServiceRegistrar, srv NotificationAPIServer) {
	// If the following call panics, it indicates UnimplementedNotificationAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotificationAPI_ServiceDesc, srv)
}

func _NotificationAPI_GetNotificationSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNotificationSummary_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationAPIServer).GetNotificationSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationAPI_GetNotificationSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationAPIServer).GetNotificationSummary(ctx, req.(*GetNotificationSummary_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationAPI_ListNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNotifications_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationAPIServer).ListNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationAPI_ListNotifications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationAPIServer).ListNotifications(ctx, req.(*ListNotifications_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationAPI_MarkNotificationRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkNotificationRead_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationAPIServer).MarkNotificationRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationAPI_MarkNotificationRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationAPIServer).MarkNotificationRead(ctx, req.(*MarkNotificationRead_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationAPI_ConsentNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsentNotification_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationAPIServer).ConsentNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationAPI_ConsentNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationAPIServer).ConsentNotification(ctx, req.(*ConsentNotification_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificationAPI_ServiceDesc is the grpc.ServiceDesc for NotificationAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zpotify_api.NotificationAPI",
	HandlerType: (*NotificationAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNotificationSummary",
			Handler:    _NotificationAPI_GetNotificationSummary_Handler,
		},
		{
			MethodName: "ListNotifications",
			Handler:    _NotificationAPI_ListNotifications_Handler,
		},
		{
			MethodName: "MarkNotificationRead",
			Handler:    _NotificationAPI_MarkNotificationRead_Handler,
		},
		{
			MethodName: "ConsentNotification",
			Handler:    _NotificationAPI_ConsentNotification_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zpotify_service_notification.proto",
}
