// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: zpotify_common.proto

package zpotify_api

import (
	_ "go.redsock.ru/protoc-gen-npm/npmplugin"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Paging struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint64                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Paging) Reset() {
	*x = Paging{}
	mi := &file_zpotify_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Paging) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Paging) ProtoMessage() {}

func (x *Paging) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Paging.ProtoReflect.Descriptor instead.
func (*Paging) Descriptor() ([]byte, []int) {
	return file_zpotify_common_proto_rawDescGZIP(), []int{0}
}

func (x *Paging) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Paging) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ArtistBase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtistBase) Reset() {
	*x = ArtistBase{}
	mi := &file_zpotify_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtistBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtistBase) ProtoMessage() {}

func (x *ArtistBase) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtistBase.ProtoReflect.Descriptor instead.
func (*ArtistBase) Descriptor() ([]byte, []int) {
	return file_zpotify_common_proto_rawDescGZIP(), []int{1}
}

func (x *ArtistBase) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ArtistBase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SongBase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Artists       []*ArtistBase          `protobuf:"bytes,3,rep,name=artists,proto3" json:"artists,omitempty"`
	DurationSec   int32                  `protobuf:"varint,4,opt,name=duration_sec,json=durationSec,proto3" json:"duration_sec,omitempty"`
	FilePath      string                 `protobuf:"bytes,5,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	FileId        int64                  `protobuf:"varint,6,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SongBase) Reset() {
	*x = SongBase{}
	mi := &file_zpotify_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SongBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SongBase) ProtoMessage() {}

func (x *SongBase) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SongBase.ProtoReflect.Descriptor instead.
func (*SongBase) Descriptor() ([]byte, []int) {
	return file_zpotify_common_proto_rawDescGZIP(), []int{2}
}

func (x *SongBase) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SongBase) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SongBase) GetArtists() []*ArtistBase {
	if x != nil {
		return x.Artists
	}
	return nil
}

func (x *SongBase) GetDurationSec() int32 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

func (x *SongBase) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *SongBase) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

type PlaylistChip struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaylistChip) Reset() {
	*x = PlaylistChip{}
	mi := &file_zpotify_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaylistChip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaylistChip) ProtoMessage() {}

func (x *PlaylistChip) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaylistChip.ProtoReflect.Descriptor instead.
func (*PlaylistChip) Descriptor() ([]byte, []int) {
	return file_zpotify_common_proto_rawDescGZIP(), []int{3}
}

func (x *PlaylistChip) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *PlaylistChip) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Playlist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	IsPublic      bool                   `protobuf:"varint,4,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	Artists       []*ArtistBase          `protobuf:"bytes,5,rep,name=artists,proto3" json:"artists,omitempty"`
	SongCount     *int32                 `protobuf:"varint,6,opt,name=song_count,json=songCount,proto3,oneof" json:"song_count,omitempty"`
	CoverFilePath *string                `protobuf:"bytes,7,opt,name=cover_file_path,json=coverFilePath,proto3,oneof" json:"cover_file_path,omitempty"`
	Year          *int32                 `protobuf:"varint,8,opt,name=year,proto3,oneof" json:"year,omitempty"`
	Chips         []*PlaylistChip        `protobuf:"bytes,9,rep,name=chips,proto3" json:"chips,omitempty"`
	CanEdit       *bool                  `protobuf:"varint,10,opt,name=can_edit,json=canEdit,proto3,oneof" json:"can_edit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Playlist) Reset() {
	*x = Playlist{}
	mi := &file_zpotify_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Playlist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Playlist) ProtoMessage() {}

func (x *Playlist) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Playlist.ProtoReflect.Descriptor instead.
func (*Playlist) Descriptor() ([]byte, []int) {
	return file_zpotify_common_proto_rawDescGZIP(), []int{4}
}

func (x *Playlist) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Playlist) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Playlist) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Playlist) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *Playlist) GetArtists() []*ArtistBase {
	if x != nil {
		return x.Artists
	}
	return nil
}

func (x *Playlist) GetSongCount() int32 {
	if x != nil && x.SongCount != nil {
		return *x.SongCount
	}
	return 0
}

func (x *Playlist) GetCoverFilePath() string {
	if x != nil && x.CoverFilePath != nil {
		return *x.CoverFilePath
	}
	return ""
}

func (x *Playlist) GetYear() int32 {
	if x != nil && x.Year != nil {
		return *x.Year
	}
	return 0
}

func (x *Playlist) GetChips() []*PlaylistChip {
	if x != nil {
		return x.Chips
	}
	return nil
}

func (x *Playlist) GetCanEdit() bool {
	if x != nil && x.CanEdit != nil {
		return *x.CanEdit
	}
	return false
}

type SongFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SongFile) Reset() {
	*x = SongFile{}
	mi := &file_zpotify_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SongFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SongFile) ProtoMessage() {}

func (x *SongFile) ProtoReflect() protoreflect.Message {
	mi := &file_zpotify_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SongFile.ProtoReflect.Descriptor instead.
func (*SongFile) Descriptor() ([]byte, []int) {
	return file_zpotify_common_proto_rawDescGZIP(), []int{5}
}

func (x *SongFile) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SongFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var File_zpotify_common_proto protoreflect.FileDescriptor

const file_zpotify_common_proto_rawDesc = "" +
	"\n" +
	"\x14zpotify_common.proto\x12\vzpotify_api\x1a\tnpm.proto\"6\n" +
	"\x06Paging\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x04R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\"4\n" +
	"\n" +
	"ArtistBase\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xbc\x01\n" +
	"\bSongBase\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x121\n" +
	"\aartists\x18\x03 \x03(\v2\x17.zpotify_api.ArtistBaseR\aartists\x12!\n" +
	"\fduration_sec\x18\x04 \x01(\x05R\vdurationSec\x12\x1b\n" +
	"\tfile_path\x18\x05 \x01(\tR\bfilePath\x12\x17\n" +
	"\afile_id\x18\x06 \x01(\x03R\x06fileId\"8\n" +
	"\fPlaylistChip\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xad\x03\n" +
	"\bPlaylist\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1b\n" +
	"\tis_public\x18\x04 \x01(\bR\bisPublic\x121\n" +
	"\aartists\x18\x05 \x03(\v2\x17.zpotify_api.ArtistBaseR\aartists\x12\"\n" +
	"\n" +
	"song_count\x18\x06 \x01(\x05H\x01R\tsongCount\x88\x01\x01\x12+\n" +
	"\x0fcover_file_path\x18\a \x01(\tH\x02R\rcoverFilePath\x88\x01\x01\x12\x17\n" +
	"\x04year\x18\b \x01(\x05H\x03R\x04year\x88\x01\x01\x12/\n" +
	"\x05chips\x18\t \x03(\v2\x19.zpotify_api.PlaylistChipR\x05chips\x12\x1e\n" +
	"\bcan_edit\x18\n" +
	" \x01(\bH\x04R\acanEdit\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_song_countB\x12\n" +
	"\x10_cover_file_pathB\a\n" +
	"\x05_yearB\v\n" +
	"\t_can_edit\".\n" +
	"\bSongFile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04pathB*\x92\x82\x19\f@zpotify/apiZ\x18/zpotify_api;zpotify_apib\x06proto3"

var (
	file_zpotify_common_proto_rawDescOnce sync.Once
	file_zpotify_common_proto_rawDescData []byte
)

func file_zpotify_common_proto_rawDescGZIP() []byte {
	file_zpotify_common_proto_rawDescOnce.Do(func() {
		file_zpotify_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zpotify_common_proto_rawDesc), len(file_zpotify_common_proto_rawDesc)))
	})
	return file_zpotify_common_proto_rawDescData
}

var file_zpotify_common_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_zpotify_common_proto_goTypes = []any{
	(*Paging)(nil),       // 0: zpotify_api.Paging
	(*ArtistBase)(nil),   // 1: zpotify_api.ArtistBase
	(*SongBase)(nil),     // 2: zpotify_api.SongBase
	(*PlaylistChip)(nil), // 3: zpotify_api.PlaylistChip
	(*Playlist)(nil),     // 4: zpotify_api.Playlist
	(*SongFile)(nil),     // 5: zpotify_api.SongFile
}
var file_zpotify_common_proto_depIdxs = []int32{
	1, // 0: zpotify_api.SongBase.artists:type_name -> zpotify_api.ArtistBase
	1, // 1: zpotify_api.Playlist.artists:type_name -> zpotify_api.ArtistBase
	3, // 2: zpotify_api.Playlist.chips:type_name -> zpotify_api.PlaylistChip
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_zpotify_common_proto_init() }
func file_zpotify_common_proto_init() {
	if File_zpotify_common_proto != nil {
		return
	}
	file_zpotify_common_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zpotify_common_proto_rawDesc), len(file_zpotify_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zpotify_common_proto_goTypes,
		DependencyIndexes: file_zpotify_common_proto_depIdxs,
		MessageInfos:      file_zpotify_common_proto_msgTypes,
	}.Build()
	File_zpotify_common_proto = out.File
	file_zpotify_common_proto_goTypes = nil
	file_zpotify_common_proto_depIdxs = nil
}
