// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.28.3
// source: zpotify_service_torrents.proto

package zpotify_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TorrentAPI_ListTorrentJobs_FullMethodName  = "/zpotify_api.TorrentAPI/ListTorrentJobs"
	TorrentAPI_GetTorrentJob_FullMethodName    = "/zpotify_api.TorrentAPI/GetTorrentJob"
	TorrentAPI_CancelTorrentJob_FullMethodName = "/zpotify_api.TorrentAPI/CancelTorrentJob"
)

// TorrentAPIClient is the client API for TorrentAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TorrentAPIClient interface {
	ListTorrentJobs(ctx context.Context, in *ListTorrentJobs_Request, opts ...grpc.CallOption) (*ListTorrentJobs_Response, error)
	GetTorrentJob(ctx context.Context, in *GetTorrentJob_Request, opts ...grpc.CallOption) (*GetTorrentJob_Response, error)
	CancelTorrentJob(ctx context.Context, in *CancelTorrentJob_Request, opts ...grpc.CallOption) (*CancelTorrentJob_Response, error)
}

type torrentAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewTorrentAPIClient(cc grpc.ClientConnInterface) TorrentAPIClient {
	return &torrentAPIClient{cc}
}

func (c *torrentAPIClient) ListTorrentJobs(ctx context.Context, in *ListTorrentJobs_Request, opts ...grpc.CallOption) (*ListTorrentJobs_Response, error) {
	out := new(ListTorrentJobs_Response)
	err := c.cc.Invoke(ctx, TorrentAPI_ListTorrentJobs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *torrentAPIClient) GetTorrentJob(ctx context.Context, in *GetTorrentJob_Request, opts ...grpc.CallOption) (*GetTorrentJob_Response, error) {
	out := new(GetTorrentJob_Response)
	err := c.cc.Invoke(ctx, TorrentAPI_GetTorrentJob_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *torrentAPIClient) CancelTorrentJob(ctx context.Context, in *CancelTorrentJob_Request, opts ...grpc.CallOption) (*CancelTorrentJob_Response, error) {
	out := new(CancelTorrentJob_Response)
	err := c.cc.Invoke(ctx, TorrentAPI_CancelTorrentJob_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TorrentAPIServer is the server API for TorrentAPI service.
// All implementations must embed UnimplementedTorrentAPIServer
// for forward compatibility
type TorrentAPIServer interface {
	ListTorrentJobs(context.Context, *ListTorrentJobs_Request) (*ListTorrentJobs_Response, error)
	GetTorrentJob(context.Context, *GetTorrentJob_Request) (*GetTorrentJob_Response, error)
	CancelTorrentJob(context.Context, *CancelTorrentJob_Request) (*CancelTorrentJob_Response, error)
	mustEmbedUnimplementedTorrentAPIServer()
}

// UnimplementedTorrentAPIServer must be embedded to have forward compatible implementations.
type UnimplementedTorrentAPIServer struct {
}

func (UnimplementedTorrentAPIServer) ListTorrentJobs(context.Context, *ListTorrentJobs_Request) (*ListTorrentJobs_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTorrentJobs not implemented")
}
func (UnimplementedTorrentAPIServer) GetTorrentJob(context.Context, *GetTorrentJob_Request) (*GetTorrentJob_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTorrentJob not implemented")
}
func (UnimplementedTorrentAPIServer) CancelTorrentJob(context.Context, *CancelTorrentJob_Request) (*CancelTorrentJob_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelTorrentJob not implemented")
}
func (UnimplementedTorrentAPIServer) mustEmbedUnimplementedTorrentAPIServer() {}

// UnsafeTorrentAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TorrentAPIServer will
// result in compilation errors.
type UnsafeTorrentAPIServer interface {
	mustEmbedUnimplementedTorrentAPIServer()
}

func RegisterTorrentAPIServer(s grpc.ServiceRegistrar, srv TorrentAPIServer) {
	s.RegisterService(&TorrentAPI_ServiceDesc, srv)
}

func _TorrentAPI_ListTorrentJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTorrentJobs_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TorrentAPIServer).ListTorrentJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TorrentAPI_ListTorrentJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TorrentAPIServer).ListTorrentJobs(ctx, req.(*ListTorrentJobs_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _TorrentAPI_GetTorrentJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTorrentJob_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TorrentAPIServer).GetTorrentJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TorrentAPI_GetTorrentJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TorrentAPIServer).GetTorrentJob(ctx, req.(*GetTorrentJob_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _TorrentAPI_CancelTorrentJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTorrentJob_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TorrentAPIServer).CancelTorrentJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TorrentAPI_CancelTorrentJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TorrentAPIServer).CancelTorrentJob(ctx, req.(*CancelTorrentJob_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// TorrentAPI_ServiceDesc is the grpc.ServiceDesc for TorrentAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TorrentAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zpotify_api.TorrentAPI",
	HandlerType: (*TorrentAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTorrentJobs",
			Handler:    _TorrentAPI_ListTorrentJobs_Handler,
		},
		{
			MethodName: "GetTorrentJob",
			Handler:    _TorrentAPI_GetTorrentJob_Handler,
		},
		{
			MethodName: "CancelTorrentJob",
			Handler:    _TorrentAPI_CancelTorrentJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zpotify_service_torrents.proto",
}
