app_info:
    name: go.zpotify.ru/zpotify
    version: v0.0.46
    startup_duration: 10s
data_sources:
    - resource_name: postgres
      migrations_folder: ./migrations
      host: localhost
      port: 5432
      user: zpotify
      pwd: ""
      name: zpotify
      ssl_mode: ""
servers:
    80:
        /{GRPC}:
            module: go.zpotify.ru/zpotify
            gateway: /api
environment:
    - name: cors_allowed_origins
      type: string
      value: '*'
    - name: debug_auth
      type: bool
      value: false
    - name: local_storage_path
      type: string
      value: /data
    - name: log_format
      type: string
      enum: [JSON, TEXT]
      value: TEXT
    - name: log_level
      type: string
      enum: [Trace, Debug, Info, Warn, Error, Fatal, Panic]
      value: Info
    - name: otel_endpoint
      type: string
      value: ""
    - name: telegram_client_id
      type: string
      value: ""
    - name: telegram_token
      type: string
      value: ""
    - name: telegram_proxy_url
      type: string
      value: ""
    - name: telegram_notifications_chat_id
      type: int
      value: 0
