app_info:
    name: go.zpotify.ru/zpotify
    version: v0.0.1
    startup_duration: 10s
data_sources:
    - resource_name: telegram
      api_key: ""
environment:
    - name: log_level
      type: string
      enum: [Trace, Debug, Info, Warn, Error, Fatal, Panic]
      value: Info
    - name: log_format
      type: string
      enum: [JSON, TEXT]
      value: TEXT
