app_info:
    name: go.zpotify.ru/zpotify
    version: v0.0.14
    startup_duration: 10s
data_sources:
    - resource_name: telegram
      api_key: ""
    - resource_name: postgres
      migrations_folder: ./migrations
      host: localhost
      port: 5432
      user: zpotify
      pwd: ""
      name: zpotify
      ssl_mode: ""
servers:
    80:
        /{GRPC}:
            module: go.zpotify.ru/zpotify
            gateway: /api
environment:
    - name: debug_auth
      type: bool
      value: false
    - name: log_format
      type: string
      enum: [JSON, TEXT]
      value: TEXT
    - name: log_level
      type: string
      enum: [Trace, Debug, Info, Warn, Error, Fatal, Panic]
      value: Info
