### FileMeta ListUploadedFiles
POST {{zpotify-api}}/api/file_meta/list
Content-Type: application/json
Authorization: {{token}}

{
  "temporary_only": true
}


### FileMeta ListUploadedFiles
GET {{zpotify-api}}/api/file_meta/5
Authorization: {{token}}
