### Upload file content
POST {{zpotify-api}}/wapi/files/upload
Authorization: {{token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="sc_1.mp3"
Content-Type: audio/mpeg

< ./data/sc_1.mp3
--WebAppBoundary--
