// Code generated by RedSock CLI. DO NOT EDIT.
package postgres

import (
	"database/sql"
	"errors"

	"go.redsock.ru/rerrors"

	"go.zpotify.ru/zpotify/internal/config"
)

func ConnectToPostgres() (*sql.DB, error) {
	cfg, err := config.Init()
	if err != nil && !errors.Is(err, config.ErrAlreadyLoaded) {
		return nil, rerrors.Wrap(err, "error loading config")
	}

	return Connect(cfg.DataSources.Postgres)
}

func MigrateToPostgres() error {
	cfg, err := config.Init()
	if err != nil && !errors.Is(err, config.ErrAlreadyLoaded) {
		return rerrors.Wrap(err, "error loading config")
	}

	return Migrate(cfg.DataSources.Postgres)
}
