// Code generated by RedSock CLI. DO NOT EDIT.

package config

type EnvironmentConfig struct {
	CorsAllowedOrigins          string
	DebugAuth                   bool
	LocalStoragePath            string
	LogFormat                   string
	LogLevel                    string
	OtelEndpoint                string
	TelegramClientID            string
	TelegramNotificationsChatID int
	TelegramProxyURL            string
	TelegramToken               string

	TorrentDownloadDir            string
	TorrentListenPort             int
	TorrentMaxConcurrentDownloads int
	TorrentSeedAfterComplete      bool
	TorrentSeedTimeLimitMinutes   int
	TorrentSyncPeriodSeconds      int
}

const (
	LogFormat_Json = "JSON"
	LogFormat_Text = "TEXT"
)

const (
	LogLevel_Trace = "Trace"
	LogLevel_Debug = "Debug"
	LogLevel_Info  = "Info"
	LogLevel_Warn  = "Warn"
	LogLevel_Error = "Error"
	LogLevel_Fatal = "Fatal"
	LogLevel_Panic = "Panic"
)
