syntax = "proto3";

package zpotify_api;

import "google/protobuf/timestamp.proto";
import "google/api/annotations.proto";
import "npm.proto";
import "zpotify_common.proto";

option go_package = "/zpotify_api;zpotify_api";
option (npm_package) = "@zpotify/api";

service ArtistsAPI {
  rpc ListArtist(ListArtist.Request) returns (ListArtist.Response) {
    option (google.api.http) = {
      post: "/api/artists/list"
      body: "*",
    };
  };

  rpc CreateArtist(CreateArtist.Request) returns (CreateArtist.Response) {
    option (google.api.http) = {
      post: "/api/artists/create"
      body: "*",
    };
  };

  rpc LikeArtist(LikeArtist.Request) returns (LikeArtist.Response) {
    option (google.api.http) = {
      post: "/api/artists/like"
      body: "*",
    };
  };

  rpc UnlikeArtist(UnlikeArtist.Request) returns (UnlikeArtist.Response) {
    option (google.api.http) = {
      post: "/api/artists/unlike"
      body: "*",
    };
  };

  rpc GetArtistPage(GetArtistPage.Request) returns (GetArtistPage.Response) {
    option (google.api.http) = {
      post: "/api/artists/get_page"
      body: "*",
    };
  };

  rpc UpdateArtist(UpdateArtist.Request) returns (UpdateArtist.Response) {
    option (google.api.http) = {
      post: "/api/artists/update"
      body: "*",
    };
  };

}

message ListArtist {
  message Request {
    Paging paging = 1;
    Filters filters = 2;
  }

  message Response {
    repeated ArtistBase artists = 1;
  }

  message Filters {
    optional string search = 1;
    optional bool only_liked = 2;
  }
}

message CreateArtist {
  message Request {
    string name = 1;
  }

  message Response {
    ArtistBase artist = 1;
  }
}

message LikeArtist {
  message Request {
    string artist_uuid = 1;
  }

  message Response {}
}

message UnlikeArtist {
  message Request {
    string artist_uuid = 1;
  }

  message Response {}
}

message Artist {
  string uuid = 1;
  string name = 2;
  bool liked = 3;
  optional string avatar_file_path = 4;
  optional string background_cover_file_path = 5;
  optional bool can_edit = 6;
}

message GetArtistPage {
  message Request {
    string artist_uuid = 1;
  }
  message Response {
    Artist artist = 1;
    repeated Playlist albums = 2;
    repeated SongBase singles = 3;
    repeated SongBase features = 4;
  }
}

message UpdateArtist {
  message Request {
    string uuid = 1;
    optional string name = 2;
    optional int64 avatar_file_id = 3;
    optional int64 background_cover_file_id = 4;
  }
  message Response {
    optional string avatar_file_path = 1;
    optional string background_cover_file_path = 2;
  }
}
